// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320_v2_1

#include "ui.h"

void ui_BLDC_5_screen_init(void)
{
    ui_BLDC_5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_5, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLDC5 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_BLDC5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLDC5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLDC5, -88);
    lv_obj_set_y(ui_BLDC5, -105);
    lv_obj_set_align(ui_BLDC5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLDC5, "SPEED BLDC 5");
    lv_obj_set_style_text_color(ui_BLDC5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLDC5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLDC5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali4 = lv_btn_create(ui_BLDC_5);
    lv_obj_set_width(ui_ButtonKembali4, 124);
    lv_obj_set_height(ui_ButtonKembali4, 34);
    lv_obj_set_x(ui_ButtonKembali4, 156);
    lv_obj_set_y(ui_ButtonKembali4, 124);
    lv_obj_set_align(ui_ButtonKembali4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali4, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali4 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_LabelKembali4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali4, 158);
    lv_obj_set_y(ui_LabelKembali4, 123);
    lv_obj_set_align(ui_LabelKembali4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali4, "RETURN");

    ui_ArcSpeed5 = lv_arc_create(ui_BLDC_5);
    lv_obj_set_width(ui_ArcSpeed5, 170);
    lv_obj_set_height(ui_ArcSpeed5, 170);
    lv_obj_set_x(ui_ArcSpeed5, -84);
    lv_obj_set_y(ui_ArcSpeed5, 24);
    lv_obj_set_align(ui_ArcSpeed5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcSpeed5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_range(ui_ArcSpeed5, 0, 180);
    lv_arc_set_value(ui_ArcSpeed5, 0);


    ui_LabelSpeed5 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_LabelSpeed5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed5, -82);
    lv_obj_set_y(ui_LabelSpeed5, -9);
    lv_obj_set_align(ui_LabelSpeed5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed5, "0");
    lv_obj_set_style_text_color(ui_LabelSpeed5, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxState8 = lv_checkbox_create(ui_BLDC_5);
    lv_checkbox_set_text(ui_CheckboxState8, "ON/OFF");
    lv_obj_set_width(ui_CheckboxState8, 90);
    lv_obj_set_height(ui_CheckboxState8, 25);
    lv_obj_set_x(ui_CheckboxState8, 154);
    lv_obj_set_y(ui_CheckboxState8, 10);
    lv_obj_set_align(ui_CheckboxState8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxState8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSpeed5 = lv_slider_create(ui_BLDC_5);
    lv_slider_set_value(ui_SliderSpeed5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed5, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed5, 209);
    lv_obj_set_height(ui_SliderSpeed5, 14);
    lv_obj_set_x(ui_SliderSpeed5, -80);
    lv_obj_set_y(ui_SliderSpeed5, 63);
    lv_obj_set_align(ui_SliderSpeed5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderSpeed5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed5, lv_color_hex(0x7DFF69), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed5, lv_color_hex(0x7DFF69), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -84);
    lv_obj_set_y(ui_Label42, -72);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "");

    ui_CheckboxState9 = lv_checkbox_create(ui_BLDC_5);
    lv_checkbox_set_text(ui_CheckboxState9, "CW/CCW");
    lv_obj_set_width(ui_CheckboxState9, 94);
    lv_obj_set_height(ui_CheckboxState9, 25);
    lv_obj_set_x(ui_CheckboxState9, 153);
    lv_obj_set_y(ui_CheckboxState9, -24);
    lv_obj_set_align(ui_CheckboxState9, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxState9, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_CheckboxState9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch9 = lv_switch_create(ui_BLDC_5);
    lv_obj_set_width(ui_Switch9, 80);
    lv_obj_set_height(ui_Switch9, 40);
    lv_obj_set_x(ui_Switch9, 159);
    lv_obj_set_y(ui_Switch9, -100);
    lv_obj_set_align(ui_Switch9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch9, lv_color_hex(0x9F9F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch9, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch9, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 161);
    lv_obj_set_y(ui_Label43, -67);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "CW/CCW");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch10 = lv_switch_create(ui_BLDC_5);
    lv_obj_set_width(ui_Switch10, 80);
    lv_obj_set_height(ui_Switch10, 40);
    lv_obj_set_x(ui_Switch10, 161);
    lv_obj_set_y(ui_Switch10, -15);
    lv_obj_set_align(ui_Switch10, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch10, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_Switch10, lv_color_hex(0x9F9F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch10, lv_color_hex(0xFF3F3F), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch10, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch10, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch10, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, 163);
    lv_obj_set_y(ui_Label44, 19);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "ON/OFF");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSimpan4 = lv_btn_create(ui_BLDC_5);
    lv_obj_set_width(ui_ButtonSimpan4, 124);
    lv_obj_set_height(ui_ButtonSimpan4, 34);
    lv_obj_set_x(ui_ButtonSimpan4, 156);
    lv_obj_set_y(ui_ButtonSimpan4, 81);
    lv_obj_set_align(ui_ButtonSimpan4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonSimpan4, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSimpan4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 156);
    lv_obj_set_y(ui_Label45, 81);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "SAVE");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMsgBox4 = lv_obj_create(ui_BLDC_5);
    lv_obj_remove_style_all(ui_ContainerMsgBox4);
    lv_obj_set_width(ui_ContainerMsgBox4, 276);
    lv_obj_set_height(ui_ContainerMsgBox4, 252);
    lv_obj_set_x(ui_ContainerMsgBox4, -67);
    lv_obj_set_y(ui_ContainerMsgBox4, -11);
    lv_obj_set_align(ui_ContainerMsgBox4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerMsgBox4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerMsgBox4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_ContainerMsgBox4);
    lv_obj_set_width(ui_Panel6, 270);
    lv_obj_set_height(ui_Panel6, 250);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, -1);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x2D3273), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_ContainerMsgBox4);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 1);
    lv_obj_set_y(ui_Label46, -24);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "SAVING DATA ?");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label46, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_btn_create(ui_ContainerMsgBox4);
    lv_obj_set_width(ui_Button19, 100);
    lv_obj_set_height(ui_Button19, 40);
    lv_obj_set_x(ui_Button19, 61);
    lv_obj_set_y(ui_Button19, 89);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button20 = lv_btn_create(ui_ContainerMsgBox4);
    lv_obj_set_width(ui_Button20, 100);
    lv_obj_set_height(ui_Button20, 40);
    lv_obj_set_x(ui_Button20, -63);
    lv_obj_set_y(ui_Button20, 89);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button20, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_ContainerMsgBox4);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, -60);
    lv_obj_set_y(ui_Label47, 88);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "CANCEL");

    ui_Label48 = lv_label_create(ui_ContainerMsgBox4);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, 60);
    lv_obj_set_y(ui_Label48, 88);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "YES");

    lv_obj_add_event_cb(ui_ButtonKembali4, ui_event_ButtonKembali4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSpeed5, ui_event_ArcSpeed5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelSpeed5, ui_event_LabelSpeed5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState8, ui_event_CheckboxState8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed5, ui_event_SliderSpeed5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSimpan4, ui_event_ButtonSimpan4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);

}
