// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320_v2_1

#include "ui.h"

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSettings,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_ScreenSettings, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_ScreenSettings, LV_DIR_BOTTOM);
    lv_obj_set_style_bg_color(ui_ScreenSettings, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView2 = lv_tabview_create(ui_ScreenSettings, LV_DIR_TOP, 36);
    lv_obj_set_width(ui_TabView2, 481);
    lv_obj_set_height(ui_TabView2, 275);
    lv_obj_set_x(ui_TabView2, -1);
    lv_obj_set_y(ui_TabView2, 21);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView2, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_STORAGE = lv_tabview_add_tab(ui_TabView2, "STORAGE");

    ui_Label82 = lv_label_create(ui_STORAGE);
    lv_obj_set_width(ui_Label82, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label82, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label82, -169);
    lv_obj_set_y(ui_Label82, -82);
    lv_obj_set_align(ui_Label82, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label82, "EEPROM");
    lv_obj_set_style_text_color(ui_Label82, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label82, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label82, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_STORAGE);
    lv_obj_set_width(ui_Button10, 120);
    lv_obj_set_height(ui_Button10, 40);
    lv_obj_set_x(ui_Button10, -149);
    lv_obj_set_y(ui_Button10, -38);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFF3644), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label83 = lv_label_create(ui_STORAGE);
    lv_obj_set_width(ui_Label83, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label83, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label83, -150);
    lv_obj_set_y(ui_Label83, -38);
    lv_obj_set_align(ui_Label83, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label83, "REMOVE DATA");
    lv_obj_set_style_text_color(ui_Label83, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label83, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label83, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label84 = lv_label_create(ui_STORAGE);
    lv_obj_set_width(ui_Label84, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label84, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label84, -118);
    lv_obj_set_y(ui_Label84, 20);
    lv_obj_set_align(ui_Label84, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label84, "FIREBASE CLOUD");
    lv_obj_set_style_text_color(ui_Label84, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label84, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label84, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button30 = lv_btn_create(ui_STORAGE);
    lv_obj_set_width(ui_Button30, 120);
    lv_obj_set_height(ui_Button30, 40);
    lv_obj_set_x(ui_Button30, -144);
    lv_obj_set_y(ui_Button30, 65);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button30, lv_color_hex(0xFF3644), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label85 = lv_label_create(ui_STORAGE);
    lv_obj_set_width(ui_Label85, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label85, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label85, -144);
    lv_obj_set_y(ui_Label85, 65);
    lv_obj_set_align(ui_Label85, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label85, "REMOVE DATA");
    lv_obj_set_style_text_color(ui_Label85, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label85, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label85, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMsgBoxREMOVEEP = lv_obj_create(ui_STORAGE);
    lv_obj_remove_style_all(ui_ContainerMsgBoxREMOVEEP);
    lv_obj_set_width(ui_ContainerMsgBoxREMOVEEP, 300);
    lv_obj_set_height(ui_ContainerMsgBoxREMOVEEP, 190);
    lv_obj_set_x(ui_ContainerMsgBoxREMOVEEP, 9);
    lv_obj_set_y(ui_ContainerMsgBoxREMOVEEP, 0);
    lv_obj_set_align(ui_ContainerMsgBoxREMOVEEP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerMsgBoxREMOVEEP, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerMsgBoxREMOVEEP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_ContainerMsgBoxREMOVEEP);
    lv_obj_set_width(ui_Panel13, 300);
    lv_obj_set_height(ui_Panel13, 190);
    lv_obj_set_x(ui_Panel13, 0);
    lv_obj_set_y(ui_Panel13, -1);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x2D3273), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label95 = lv_label_create(ui_ContainerMsgBoxREMOVEEP);
    lv_obj_set_width(ui_Label95, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label95, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label95, 1);
    lv_obj_set_y(ui_Label95, -24);
    lv_obj_set_align(ui_Label95, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label95, "REMOVE DATA ?");
    lv_obj_set_style_text_color(ui_Label95, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label95, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label95, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button35 = lv_btn_create(ui_ContainerMsgBoxREMOVEEP);
    lv_obj_set_width(ui_Button35, 100);
    lv_obj_set_height(ui_Button35, 40);
    lv_obj_set_x(ui_Button35, 61);
    lv_obj_set_y(ui_Button35, 64);
    lv_obj_set_align(ui_Button35, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button35, lv_color_hex(0xFF3644), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button33 = lv_btn_create(ui_ContainerMsgBoxREMOVEEP);
    lv_obj_set_width(ui_Button33, 100);
    lv_obj_set_height(ui_Button33, 40);
    lv_obj_set_x(ui_Button33, -63);
    lv_obj_set_y(ui_Button33, 64);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button33, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label92 = lv_label_create(ui_ContainerMsgBoxREMOVEEP);
    lv_obj_set_width(ui_Label92, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label92, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label92, -59);
    lv_obj_set_y(ui_Label92, 64);
    lv_obj_set_align(ui_Label92, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label92, "CANCEL");

    ui_Label93 = lv_label_create(ui_ContainerMsgBoxREMOVEEP);
    lv_obj_set_width(ui_Label93, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label93, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label93, 60);
    lv_obj_set_y(ui_Label93, 66);
    lv_obj_set_align(ui_Label93, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label93, "YES");

    ui_ContainerMsgBoxREMOVEFB = lv_obj_create(ui_STORAGE);
    lv_obj_remove_style_all(ui_ContainerMsgBoxREMOVEFB);
    lv_obj_set_width(ui_ContainerMsgBoxREMOVEFB, 300);
    lv_obj_set_height(ui_ContainerMsgBoxREMOVEFB, 190);
    lv_obj_set_x(ui_ContainerMsgBoxREMOVEFB, 9);
    lv_obj_set_y(ui_ContainerMsgBoxREMOVEFB, 0);
    lv_obj_set_align(ui_ContainerMsgBoxREMOVEFB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerMsgBoxREMOVEFB, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerMsgBoxREMOVEFB, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel15 = lv_obj_create(ui_ContainerMsgBoxREMOVEFB);
    lv_obj_set_width(ui_Panel15, 300);
    lv_obj_set_height(ui_Panel15, 190);
    lv_obj_set_x(ui_Panel15, 0);
    lv_obj_set_y(ui_Panel15, -1);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x2D3273), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label99 = lv_label_create(ui_ContainerMsgBoxREMOVEFB);
    lv_obj_set_width(ui_Label99, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label99, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label99, 1);
    lv_obj_set_y(ui_Label99, -24);
    lv_obj_set_align(ui_Label99, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label99, "REMOVE DATA ?");
    lv_obj_set_style_text_color(ui_Label99, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label99, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label99, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button38 = lv_btn_create(ui_ContainerMsgBoxREMOVEFB);
    lv_obj_set_width(ui_Button38, 100);
    lv_obj_set_height(ui_Button38, 40);
    lv_obj_set_x(ui_Button38, 61);
    lv_obj_set_y(ui_Button38, 64);
    lv_obj_set_align(ui_Button38, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button38, lv_color_hex(0xFF3644), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button39 = lv_btn_create(ui_ContainerMsgBoxREMOVEFB);
    lv_obj_set_width(ui_Button39, 100);
    lv_obj_set_height(ui_Button39, 40);
    lv_obj_set_x(ui_Button39, -63);
    lv_obj_set_y(ui_Button39, 64);
    lv_obj_set_align(ui_Button39, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button39, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label100 = lv_label_create(ui_ContainerMsgBoxREMOVEFB);
    lv_obj_set_width(ui_Label100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label100, -59);
    lv_obj_set_y(ui_Label100, 64);
    lv_obj_set_align(ui_Label100, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label100, "CANCEL");

    ui_Label101 = lv_label_create(ui_ContainerMsgBoxREMOVEFB);
    lv_obj_set_width(ui_Label101, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label101, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label101, 60);
    lv_obj_set_y(ui_Label101, 66);
    lv_obj_set_align(ui_Label101, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label101, "YES");

    ui_WIFI = lv_tabview_add_tab(ui_TabView2, "WIFI");
    lv_obj_add_flag(ui_WIFI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_scroll_dir(ui_WIFI, LV_DIR_BOTTOM);

    ui_Label86 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label86, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label86, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label86, -149);
    lv_obj_set_y(ui_Label86, -87);
    lv_obj_set_align(ui_Label86, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label86, "ACCESS POINT");
    lv_obj_set_style_text_color(ui_Label86, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label86, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label87 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label87, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label87, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label87, -170);
    lv_obj_set_y(ui_Label87, -34);
    lv_obj_set_align(ui_Label87, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label87, "SSID");
    lv_obj_set_style_text_color(ui_Label87, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label87, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label88 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label88, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label88, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label88, -116);
    lv_obj_set_y(ui_Label88, -34);
    lv_obj_set_align(ui_Label88, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label88, ":");
    lv_obj_set_style_text_color(ui_Label88, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label88, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label89 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label89, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label89, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label89, -167);
    lv_obj_set_y(ui_Label89, 19);
    lv_obj_set_align(ui_Label89, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label89, "PASS");
    lv_obj_set_style_text_color(ui_Label89, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label89, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label90 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label90, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label90, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label90, -116);
    lv_obj_set_y(ui_Label90, 18);
    lv_obj_set_align(ui_Label90, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label90, ":");
    lv_obj_set_style_text_color(ui_Label90, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label90, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_WIFI);
    lv_obj_set_width(ui_TextArea2, 193);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_TextArea2, -1);
    lv_obj_set_y(ui_TextArea2, -33);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "SSID WIFI");
    lv_textarea_set_one_line(ui_TextArea2, true);



    ui_TextArea3 = lv_textarea_create(ui_WIFI);
    lv_obj_set_width(ui_TextArea3, 193);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_TextArea3, 2);
    lv_obj_set_y(ui_TextArea3, 20);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "PASSWORD");
    lv_textarea_set_one_line(ui_TextArea3, true);



    ui_Button32 = lv_btn_create(ui_WIFI);
    lv_obj_set_width(ui_Button32, 100);
    lv_obj_set_height(ui_Button32, 38);
    lv_obj_set_x(ui_Button32, -42);
    lv_obj_set_y(ui_Button32, 72);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button32, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label91 = lv_label_create(ui_WIFI);
    lv_obj_set_width(ui_Label91, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label91, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label91, -43);
    lv_obj_set_y(ui_Label91, 73);
    lv_obj_set_align(ui_Label91, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label91, "SAVE");

    ui_ContainerMsgBoxWIFI = lv_obj_create(ui_WIFI);
    lv_obj_remove_style_all(ui_ContainerMsgBoxWIFI);
    lv_obj_set_width(ui_ContainerMsgBoxWIFI, 300);
    lv_obj_set_height(ui_ContainerMsgBoxWIFI, 190);
    lv_obj_set_x(ui_ContainerMsgBoxWIFI, 9);
    lv_obj_set_y(ui_ContainerMsgBoxWIFI, 0);
    lv_obj_set_align(ui_ContainerMsgBoxWIFI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerMsgBoxWIFI, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerMsgBoxWIFI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel14 = lv_obj_create(ui_ContainerMsgBoxWIFI);
    lv_obj_set_width(ui_Panel14, 300);
    lv_obj_set_height(ui_Panel14, 190);
    lv_obj_set_x(ui_Panel14, 0);
    lv_obj_set_y(ui_Panel14, -1);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x2D3273), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label98 = lv_label_create(ui_ContainerMsgBoxWIFI);
    lv_obj_set_width(ui_Label98, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label98, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label98, 1);
    lv_obj_set_y(ui_Label98, -24);
    lv_obj_set_align(ui_Label98, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label98, "SAVING DATA ?");
    lv_obj_set_style_text_color(ui_Label98, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label98, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label98, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button37 = lv_btn_create(ui_ContainerMsgBoxWIFI);
    lv_obj_set_width(ui_Button37, 100);
    lv_obj_set_height(ui_Button37, 40);
    lv_obj_set_x(ui_Button37, 61);
    lv_obj_set_y(ui_Button37, 64);
    lv_obj_set_align(ui_Button37, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button37, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button34 = lv_btn_create(ui_ContainerMsgBoxWIFI);
    lv_obj_set_width(ui_Button34, 100);
    lv_obj_set_height(ui_Button34, 40);
    lv_obj_set_x(ui_Button34, -63);
    lv_obj_set_y(ui_Button34, 64);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button34, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label94 = lv_label_create(ui_ContainerMsgBoxWIFI);
    lv_obj_set_width(ui_Label94, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label94, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label94, -59);
    lv_obj_set_y(ui_Label94, 64);
    lv_obj_set_align(ui_Label94, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label94, "CANCEL");

    ui_Label96 = lv_label_create(ui_ContainerMsgBoxWIFI);
    lv_obj_set_width(ui_Label96, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label96, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label96, 60);
    lv_obj_set_y(ui_Label96, 66);
    lv_obj_set_align(ui_Label96, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label96, "YES");

    ui_Keyboard2 = lv_keyboard_create(ui_WIFI);
    lv_obj_set_width(ui_Keyboard2, 477);
    lv_obj_set_height(ui_Keyboard2, 212);
    lv_obj_set_x(ui_Keyboard2, 1);
    lv_obj_set_y(ui_Keyboard2, 15);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Label79 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label79, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label79, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label79, 3);
    lv_obj_set_y(ui_Label79, -141);
    lv_obj_set_align(ui_Label79, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label79, "SETTINGS");
    lv_obj_set_style_text_color(ui_Label79, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label79, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label79, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali12 = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonKembali12, 100);
    lv_obj_set_height(ui_ButtonKembali12, 34);
    lv_obj_set_x(ui_ButtonKembali12, -186);
    lv_obj_set_y(ui_ButtonKembali12, -140);
    lv_obj_set_align(ui_ButtonKembali12, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali12, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label81 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label81, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label81, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label81, -188);
    lv_obj_set_y(ui_Label81, -141);
    lv_obj_set_align(ui_Label81, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label81, "RETURN");
    lv_obj_set_style_text_font(ui_Label81, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button30, ui_event_Button30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button35, ui_event_Button35, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button33, ui_event_Button33, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button38, ui_event_Button38, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button39, ui_event_Button39, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button32, ui_event_Button32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button37, ui_event_Button37, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button34, ui_event_Button34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonKembali12, ui_event_ButtonKembali12, LV_EVENT_ALL, NULL);

}
