// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320_v2_1

#include "ui.h"

void ui_WIFI_Screen_screen_init(void)
{
    ui_WIFI_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WIFI_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFI_Screen, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFI_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_Panel22, 478);
    lv_obj_set_height(ui_Panel22, 315);
    lv_obj_set_x(ui_Panel22, 1);
    lv_obj_set_y(ui_Panel22, -1);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel22, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel22, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel22, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel22, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali10 = lv_btn_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_ButtonKembali10, 124);
    lv_obj_set_height(ui_ButtonKembali10, 34);
    lv_obj_set_x(ui_ButtonKembali10, 156);
    lv_obj_set_y(ui_ButtonKembali10, 124);
    lv_obj_set_align(ui_ButtonKembali10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali10, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali10 = lv_label_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_LabelKembali10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali10, 158);
    lv_obj_set_y(ui_LabelKembali10, 123);
    lv_obj_set_align(ui_LabelKembali10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali10, "RETURN");

    ui_Dropdown1 = lv_dropdown_create(ui_WIFI_Screen);
    lv_dropdown_set_options(ui_Dropdown1, "SSID WIFI");
    lv_obj_set_width(ui_Dropdown1, 260);
    lv_obj_set_height(ui_Dropdown1, 38);
    lv_obj_set_x(ui_Dropdown1, 63);
    lv_obj_set_y(ui_Dropdown1, -48);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label11 = lv_label_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -128);
    lv_obj_set_y(ui_Label11, -50);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "WIFI");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -91);
    lv_obj_set_y(ui_Label12, -50);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, ":");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_TextArea1, 260);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_TextArea1, 64);
    lv_obj_set_y(ui_TextArea1, 3);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    if("*" == "") lv_textarea_set_accepted_chars(ui_TextArea1, NULL);
    else lv_textarea_set_accepted_chars(ui_TextArea1, "*");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Password");
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_textarea_set_password_mode(ui_TextArea1, true);



    ui_Label22 = lv_label_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -161);
    lv_obj_set_y(ui_Label22, -1);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "PASSWORD");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -89);
    lv_obj_set_y(ui_Label23, -2);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, ":");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali9 = lv_btn_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_ButtonKembali9, 124);
    lv_obj_set_height(ui_ButtonKembali9, 34);
    lv_obj_set_x(ui_ButtonKembali9, -2);
    lv_obj_set_y(ui_ButtonKembali9, 55);
    lv_obj_set_align(ui_ButtonKembali9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali9, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali9 = lv_label_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_LabelKembali9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali9, -2);
    lv_obj_set_y(ui_LabelKembali9, 55);
    lv_obj_set_align(ui_LabelKembali9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali9, "SAVE");

    ui_Keyboard1 = lv_keyboard_create(ui_WIFI_Screen);
    lv_obj_set_width(ui_Keyboard1, 474);
    lv_obj_set_height(ui_Keyboard1, 196);
    lv_obj_set_x(ui_Keyboard1, 1);
    lv_obj_set_y(ui_Keyboard1, 57);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMsgBox10 = lv_obj_create(ui_WIFI_Screen);
    lv_obj_remove_style_all(ui_ContainerMsgBox10);
    lv_obj_set_width(ui_ContainerMsgBox10, 276);
    lv_obj_set_height(ui_ContainerMsgBox10, 252);
    lv_obj_set_x(ui_ContainerMsgBox10, -10);
    lv_obj_set_y(ui_ContainerMsgBox10, -13);
    lv_obj_set_align(ui_ContainerMsgBox10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerMsgBox10, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerMsgBox10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_ContainerMsgBox10);
    lv_obj_set_width(ui_Panel12, 270);
    lv_obj_set_height(ui_Panel12, 250);
    lv_obj_set_x(ui_Panel12, 0);
    lv_obj_set_y(ui_Panel12, -1);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x2D3273), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label80 = lv_label_create(ui_ContainerMsgBox10);
    lv_obj_set_width(ui_Label80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label80, 1);
    lv_obj_set_y(ui_Label80, -24);
    lv_obj_set_align(ui_Label80, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label80, "SAVING DATA ?");
    lv_obj_set_style_text_color(ui_Label80, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label80, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button31 = lv_btn_create(ui_ContainerMsgBox10);
    lv_obj_set_width(ui_Button31, 100);
    lv_obj_set_height(ui_Button31, 40);
    lv_obj_set_x(ui_Button31, 61);
    lv_obj_set_y(ui_Button31, 89);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button31, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button29 = lv_btn_create(ui_ContainerMsgBox10);
    lv_obj_set_width(ui_Button29, 100);
    lv_obj_set_height(ui_Button29, 40);
    lv_obj_set_x(ui_Button29, -63);
    lv_obj_set_y(ui_Button29, 89);
    lv_obj_set_align(ui_Button29, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button29, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Button29, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label77 = lv_label_create(ui_ContainerMsgBox10);
    lv_obj_set_width(ui_Label77, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label77, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label77, -60);
    lv_obj_set_y(ui_Label77, 88);
    lv_obj_set_align(ui_Label77, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label77, "CANCEL");

    ui_Label78 = lv_label_create(ui_ContainerMsgBox10);
    lv_obj_set_width(ui_Label78, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label78, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label78, 60);
    lv_obj_set_y(ui_Label78, 88);
    lv_obj_set_align(ui_Label78, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label78, "YES");

    lv_obj_add_event_cb(ui_ButtonKembali10, ui_event_ButtonKembali10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonKembali9, ui_event_ButtonKembali9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button31, ui_event_Button31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button29, ui_event_Button29, LV_EVENT_ALL, NULL);

}
