// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320_v2_2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Panel23;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_KONTROL_BLDC;
lv_obj_t * ui_Image3;
lv_obj_t * ui_LabelTemp;
lv_obj_t * ui_Suhu;
lv_obj_t * ui_Image1;
lv_obj_t * ui_LabelSpeed;
lv_obj_t * ui_Kecepatan;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Tekanan;
lv_obj_t * ui_LabelPress;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Kebisingan;
lv_obj_t * ui_LabelNoise;
lv_obj_t * ui_LebelState1;
lv_obj_t * ui_LebelState2;
lv_obj_t * ui_LebelState3;
lv_obj_t * ui_LebelState4;
lv_obj_t * ui_LebelState5;
lv_obj_t * ui_LebelState6;
lv_obj_t * ui_LebelState7;
lv_obj_t * ui_LebelState8;
lv_obj_t * ui_LebelState9;
lv_obj_t * ui_STATUS;
void ui_event_ButtonWifi1(lv_event_t * e);
lv_obj_t * ui_ButtonWifi1;
lv_obj_t * ui_Image6;


// SCREEN: ui_BLDC_1
void ui_BLDC_1_screen_init(void);
lv_obj_t * ui_BLDC_1;
lv_obj_t * ui_BLDC1;
void ui_event_ButtonKembali(lv_event_t * e);
lv_obj_t * ui_ButtonKembali;
lv_obj_t * ui_LabelKembali;
void ui_event_ArcSpeed1(lv_event_t * e);
lv_obj_t * ui_ArcSpeed1;
void ui_event_LabelSpeed1(lv_event_t * e);
lv_obj_t * ui_LabelSpeed1;
void ui_event_CheckboxState1(lv_event_t * e);
lv_obj_t * ui_CheckboxState1;
void ui_event_SliderSpeed1(lv_event_t * e);
lv_obj_t * ui_SliderSpeed1;
lv_obj_t * ui_Label13;
lv_obj_t * ui_CheckboxState10;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Label24;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Label25;
void ui_event_ButtonSimpan(lv_event_t * e);
lv_obj_t * ui_ButtonSimpan;
lv_obj_t * ui_Label10;
lv_obj_t * ui_ContainerMsgBox;
lv_obj_t * ui_Panel24;
lv_obj_t * ui_Label28;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label26;


// SCREEN: ui_BLDC_2
void ui_BLDC_2_screen_init(void);
lv_obj_t * ui_BLDC_2;
lv_obj_t * ui_BLDC2;
void ui_event_ButtonKembali1(lv_event_t * e);
lv_obj_t * ui_ButtonKembali1;
lv_obj_t * ui_LabelKembali1;
void ui_event_ArcSpeed2(lv_event_t * e);
lv_obj_t * ui_ArcSpeed2;
void ui_event_LabelSpeed2(lv_event_t * e);
lv_obj_t * ui_LabelSpeed2;
void ui_event_CheckboxState2(lv_event_t * e);
lv_obj_t * ui_CheckboxState2;
void ui_event_SliderSpeed2(lv_event_t * e);
lv_obj_t * ui_SliderSpeed2;
lv_obj_t * ui_Label14;
lv_obj_t * ui_CheckboxState3;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Label15;
void ui_event_Switch4(lv_event_t * e);
lv_obj_t * ui_Switch4;
lv_obj_t * ui_Label16;
void ui_event_ButtonSimpan1(lv_event_t * e);
lv_obj_t * ui_ButtonSimpan1;
lv_obj_t * ui_Label17;
lv_obj_t * ui_ContainerMsgBox1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label18;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;


// SCREEN: ui_BLDC_3
void ui_BLDC_3_screen_init(void);
lv_obj_t * ui_BLDC_3;
lv_obj_t * ui_BLDC3;
void ui_event_ButtonKembali2(lv_event_t * e);
lv_obj_t * ui_ButtonKembali2;
lv_obj_t * ui_LabelKembali2;
void ui_event_ArcSpeed3(lv_event_t * e);
lv_obj_t * ui_ArcSpeed3;
void ui_event_LabelSpeed3(lv_event_t * e);
lv_obj_t * ui_LabelSpeed3;
void ui_event_CheckboxState4(lv_event_t * e);
lv_obj_t * ui_CheckboxState4;
void ui_event_SliderSpeed3(lv_event_t * e);
lv_obj_t * ui_SliderSpeed3;
lv_obj_t * ui_Label21;
lv_obj_t * ui_CheckboxState5;
void ui_event_Switch5(lv_event_t * e);
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Label29;
void ui_event_Switch6(lv_event_t * e);
lv_obj_t * ui_Switch6;
lv_obj_t * ui_Label30;
void ui_event_ButtonSimpan2(lv_event_t * e);
lv_obj_t * ui_ButtonSimpan2;
lv_obj_t * ui_Label31;
lv_obj_t * ui_ContainerMsgBox2;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label32;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;


// SCREEN: ui_BLDC_4
void ui_BLDC_4_screen_init(void);
lv_obj_t * ui_BLDC_4;
lv_obj_t * ui_BLDC4;
void ui_event_ButtonKembali3(lv_event_t * e);
lv_obj_t * ui_ButtonKembali3;
lv_obj_t * ui_LabelKembali3;
void ui_event_ArcSpeed4(lv_event_t * e);
lv_obj_t * ui_ArcSpeed4;
void ui_event_LabelSpeed4(lv_event_t * e);
lv_obj_t * ui_LabelSpeed4;
void ui_event_CheckboxState6(lv_event_t * e);
lv_obj_t * ui_CheckboxState6;
void ui_event_SliderSpeed4(lv_event_t * e);
lv_obj_t * ui_SliderSpeed4;
lv_obj_t * ui_Label35;
lv_obj_t * ui_CheckboxState7;
void ui_event_Switch7(lv_event_t * e);
lv_obj_t * ui_Switch7;
lv_obj_t * ui_Label36;
void ui_event_Switch8(lv_event_t * e);
lv_obj_t * ui_Switch8;
lv_obj_t * ui_Label37;
void ui_event_ButtonSimpan3(lv_event_t * e);
lv_obj_t * ui_ButtonSimpan3;
lv_obj_t * ui_Label38;
lv_obj_t * ui_ContainerMsgBox3;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label39;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Label41;


// SCREEN: ui_BLDC_5
void ui_BLDC_5_screen_init(void);
lv_obj_t * ui_BLDC_5;
lv_obj_t * ui_BLDC5;
void ui_event_ButtonKembali4(lv_event_t * e);
lv_obj_t * ui_ButtonKembali4;
lv_obj_t * ui_LabelKembali4;
void ui_event_ArcSpeed5(lv_event_t * e);
lv_obj_t * ui_ArcSpeed5;
void ui_event_LabelSpeed5(lv_event_t * e);
lv_obj_t * ui_LabelSpeed5;
void ui_event_CheckboxState8(lv_event_t * e);
lv_obj_t * ui_CheckboxState8;
void ui_event_SliderSpeed5(lv_event_t * e);
lv_obj_t * ui_SliderSpeed5;
lv_obj_t * ui_Label42;
lv_obj_t * ui_CheckboxState9;
void ui_event_Switch9(lv_event_t * e);
lv_obj_t * ui_Switch9;
lv_obj_t * ui_Label43;
void ui_event_Switch10(lv_event_t * e);
lv_obj_t * ui_Switch10;
lv_obj_t * ui_Label44;
void ui_event_ButtonSimpan4(lv_event_t * e);
lv_obj_t * ui_ButtonSimpan4;
lv_obj_t * ui_Label45;
lv_obj_t * ui_ContainerMsgBox4;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label46;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Label48;


// SCREEN: ui_BLDC_6
void ui_BLDC_6_screen_init(void);
lv_obj_t * ui_BLDC_6;
lv_obj_t * ui_BLDC6;
void ui_event_ButtonKembali5(lv_event_t * e);
lv_obj_t * ui_ButtonKembali5;
lv_obj_t * ui_LabelKembali5;
void ui_event_ArcSpeed6(lv_event_t * e);
lv_obj_t * ui_ArcSpeed6;
void ui_event_LabelSpeed6(lv_event_t * e);
lv_obj_t * ui_LabelSpeed6;
void ui_event_CheckboxState11(lv_event_t * e);
lv_obj_t * ui_CheckboxState11;
void ui_event_SliderSpeed6(lv_event_t * e);
lv_obj_t * ui_SliderSpeed6;
lv_obj_t * ui_Label49;
lv_obj_t * ui_CheckboxState12;
void ui_event_Switch11(lv_event_t * e);
lv_obj_t * ui_Switch11;
lv_obj_t * ui_Label50;
void ui_event_Switch12(lv_event_t * e);
lv_obj_t * ui_Switch12;
lv_obj_t * ui_Label51;
void ui_event_ButtonSimpan5(lv_event_t * e);
lv_obj_t * ui_ButtonSimpan5;
lv_obj_t * ui_Label52;
lv_obj_t * ui_ContainerMsgBox5;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label53;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label54;
lv_obj_t * ui_Label55;


// SCREEN: ui_BLDC_7
void ui_BLDC_7_screen_init(void);
lv_obj_t * ui_BLDC_7;
lv_obj_t * ui_BLDC7;
void ui_event_ButtonKembali6(lv_event_t * e);
lv_obj_t * ui_ButtonKembali6;
lv_obj_t * ui_LabelKembali6;
void ui_event_ArcSpeed7(lv_event_t * e);
lv_obj_t * ui_ArcSpeed7;
void ui_event_LabelSpeed7(lv_event_t * e);
lv_obj_t * ui_LabelSpeed7;
void ui_event_CheckboxState13(lv_event_t * e);
lv_obj_t * ui_CheckboxState13;
void ui_event_SliderSpeed7(lv_event_t * e);
lv_obj_t * ui_SliderSpeed7;
lv_obj_t * ui_Label56;
lv_obj_t * ui_CheckboxState14;
void ui_event_Switch13(lv_event_t * e);
lv_obj_t * ui_Switch13;
lv_obj_t * ui_Label57;
void ui_event_Switch14(lv_event_t * e);
lv_obj_t * ui_Switch14;
lv_obj_t * ui_Label58;
void ui_event_ButtonSimpan6(lv_event_t * e);
lv_obj_t * ui_ButtonSimpan6;
lv_obj_t * ui_Label59;
lv_obj_t * ui_ContainerMsgBox6;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label60;
void ui_event_Button23(lv_event_t * e);
lv_obj_t * ui_Button23;
void ui_event_Button24(lv_event_t * e);
lv_obj_t * ui_Button24;
lv_obj_t * ui_Label61;
lv_obj_t * ui_Label62;


// SCREEN: ui_BLDC_8
void ui_BLDC_8_screen_init(void);
lv_obj_t * ui_BLDC_8;
lv_obj_t * ui_BLDC8;
void ui_event_ButtonKembali7(lv_event_t * e);
lv_obj_t * ui_ButtonKembali7;
lv_obj_t * ui_LabelKembali7;
void ui_event_ArcSpeed8(lv_event_t * e);
lv_obj_t * ui_ArcSpeed8;
void ui_event_LabelSpeed8(lv_event_t * e);
lv_obj_t * ui_LabelSpeed8;
void ui_event_CheckboxState15(lv_event_t * e);
lv_obj_t * ui_CheckboxState15;
void ui_event_SliderSpeed8(lv_event_t * e);
lv_obj_t * ui_SliderSpeed8;
lv_obj_t * ui_Label63;
lv_obj_t * ui_CheckboxState16;
void ui_event_Switch15(lv_event_t * e);
lv_obj_t * ui_Switch15;
lv_obj_t * ui_Label64;
void ui_event_Switch16(lv_event_t * e);
lv_obj_t * ui_Switch16;
lv_obj_t * ui_Label65;
void ui_event_ButtonSimpan7(lv_event_t * e);
lv_obj_t * ui_ButtonSimpan7;
lv_obj_t * ui_Label66;
lv_obj_t * ui_ContainerMsgBox7;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label67;
void ui_event_Button25(lv_event_t * e);
lv_obj_t * ui_Button25;
void ui_event_Button26(lv_event_t * e);
lv_obj_t * ui_Button26;
lv_obj_t * ui_Label68;
lv_obj_t * ui_Label69;


// SCREEN: ui_BLDC_9
void ui_BLDC_9_screen_init(void);
lv_obj_t * ui_BLDC_9;
lv_obj_t * ui_BLDC9;
void ui_event_ButtonKembali8(lv_event_t * e);
lv_obj_t * ui_ButtonKembali8;
lv_obj_t * ui_LabelKembali8;
void ui_event_ArcSpeed9(lv_event_t * e);
lv_obj_t * ui_ArcSpeed9;
void ui_event_LabelSpeed9(lv_event_t * e);
lv_obj_t * ui_LabelSpeed9;
void ui_event_CheckboxState17(lv_event_t * e);
lv_obj_t * ui_CheckboxState17;
void ui_event_SliderSpeed9(lv_event_t * e);
lv_obj_t * ui_SliderSpeed9;
lv_obj_t * ui_Label70;
lv_obj_t * ui_CheckboxState18;
void ui_event_Switch17(lv_event_t * e);
lv_obj_t * ui_Switch17;
lv_obj_t * ui_Label71;
void ui_event_Switch18(lv_event_t * e);
lv_obj_t * ui_Switch18;
lv_obj_t * ui_Label72;
void ui_event_ButtonSimpan8(lv_event_t * e);
lv_obj_t * ui_ButtonSimpan8;
lv_obj_t * ui_Label73;
lv_obj_t * ui_ContainerMsgBox8;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label74;
void ui_event_Button27(lv_event_t * e);
lv_obj_t * ui_Button27;
void ui_event_Button28(lv_event_t * e);
lv_obj_t * ui_Button28;
lv_obj_t * ui_Label75;
lv_obj_t * ui_Label76;


// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
lv_obj_t * ui_ScreenSettings;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_STORAGE;
lv_obj_t * ui_Label82;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label83;
lv_obj_t * ui_Label84;
void ui_event_Button30(lv_event_t * e);
lv_obj_t * ui_Button30;
lv_obj_t * ui_Label85;
lv_obj_t * ui_ContainerMsgBoxREMOVEEP;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label95;
void ui_event_Button35(lv_event_t * e);
lv_obj_t * ui_Button35;
void ui_event_Button33(lv_event_t * e);
lv_obj_t * ui_Button33;
lv_obj_t * ui_Label92;
lv_obj_t * ui_Label93;
lv_obj_t * ui_ContainerMsgBoxREMOVEFB;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Label99;
void ui_event_Button38(lv_event_t * e);
lv_obj_t * ui_Button38;
void ui_event_Button39(lv_event_t * e);
lv_obj_t * ui_Button39;
lv_obj_t * ui_Label100;
lv_obj_t * ui_Label101;
lv_obj_t * ui_WIFI;
lv_obj_t * ui_Label86;
lv_obj_t * ui_Label87;
lv_obj_t * ui_Label88;
lv_obj_t * ui_Label89;
lv_obj_t * ui_Label90;
void ui_event_TextArea2(lv_event_t * e);
lv_obj_t * ui_TextArea2;
void ui_event_TextArea3(lv_event_t * e);
lv_obj_t * ui_TextArea3;
void ui_event_Button32(lv_event_t * e);
lv_obj_t * ui_Button32;
lv_obj_t * ui_Label91;
lv_obj_t * ui_ContainerMsgBoxWIFI;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label98;
void ui_event_Button37(lv_event_t * e);
lv_obj_t * ui_Button37;
void ui_event_Button34(lv_event_t * e);
lv_obj_t * ui_Button34;
lv_obj_t * ui_Label94;
lv_obj_t * ui_Label96;
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_Label79;
void ui_event_ButtonKembali12(lv_event_t * e);
lv_obj_t * ui_ButtonKembali12;
lv_obj_t * ui_Label81;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_29274618[1] = {&ui_img_1318045025};
const lv_img_dsc_t * ui_imgset_1548403577[1] = {&ui_img_112426812};
const lv_img_dsc_t * ui_imgset_219479303[1] = {&ui_img_777776686};
const lv_img_dsc_t * ui_imgset_509167910[1] = {&ui_img_1782230515};
const lv_img_dsc_t * ui_imgset_1703005419[1] = {&ui_img_2047884213};
const lv_img_dsc_t * ui_imgset_1655372527[1] = {&ui_img_1924603646};
const lv_img_dsc_t * ui_imgset_1516266718[1] = {&ui_img_1754639307};
const lv_img_dsc_t * ui_imgset_171687932[1] = {&ui_img_1377203910};
const lv_img_dsc_t * ui_imgset_535857063[1] = {&ui_img_475571255};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BLDC_1, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_BLDC_1_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BLDC_2, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_BLDC_2_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BLDC_3, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_BLDC_3_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BLDC_4, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_BLDC_4_screen_init);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BLDC_5, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_BLDC_5_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BLDC_6, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_BLDC_6_screen_init);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BLDC_7, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_BLDC_7_screen_init);
    }
}
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BLDC_8, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_BLDC_8_screen_init);
    }
}
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BLDC_9, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_BLDC_9_screen_init);
    }
}
void ui_event_ButtonWifi1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 10, 0, &ui_ScreenSettings_screen_init);
    }
}
void ui_event_ButtonKembali(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ArcSpeed1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed1, target, "", "");
    }
}
void ui_event_LabelSpeed1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed1, target, "", "");
    }
}
void ui_event_CheckboxState1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}
// void ui_event_SliderSpeed1(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED) {
//         _ui_slider_set_text_value(ui_LabelSpeed1, target, "", "");
//     }
// }
// void ui_event_Switch2(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT CW/CCW");
//     }
// }
// void ui_event_Switch1(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
//         _ui_label_set_property(ui_BLDC1, _UI_LABEL_PROPERTY_TEXT, "ON");
//     }
//     if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
//         _ui_label_set_property(ui_BLDC1, _UI_LABEL_PROPERTY_TEXT, "OFF");
//     }
// }
void ui_event_ButtonSimpan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBox, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
// void ui_event_Button14(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_Button15(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }

void ui_event_ButtonKembali1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ArcSpeed2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed2, target, "", "");
    }
}
void ui_event_LabelSpeed2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed2, target, "", "");
    }
}
void ui_event_CheckboxState2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}
// void ui_event_SliderSpeed2(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED) {
//         _ui_slider_set_text_value(ui_LabelSpeed2, target, "", "");
//     }
// }
// void ui_event_Switch3(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT CW/CCW1");
//     }
// }
// void ui_event_Switch4(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT ON/OFF1");
//     }
// }
void ui_event_ButtonSimpan1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBox1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
// void ui_event_Button11(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_Button12(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
void ui_event_ButtonKembali2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ArcSpeed3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed3, target, "", "");
    }
}
void ui_event_LabelSpeed3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed3, target, "", "");
    }
}
void ui_event_CheckboxState4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}
// void ui_event_SliderSpeed3(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED) {
//         _ui_slider_set_text_value(ui_LabelSpeed3, target, "", "");
//     }
// }
// void ui_event_Switch5(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT CW/CCW1");
//     }
// }
// void ui_event_Switch6(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT ON/OFF1");
//     }
// }
void ui_event_ButtonSimpan2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBox2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
// void ui_event_Button13(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_Button16(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
void ui_event_ButtonKembali3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ArcSpeed4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed4, target, "", "");
    }
}
void ui_event_LabelSpeed4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed4, target, "", "");
    }
}
void ui_event_CheckboxState6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}
// void ui_event_SliderSpeed4(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED) {
//         _ui_slider_set_text_value(ui_LabelSpeed4, target, "", "");
//     }
// }
// void ui_event_Switch7(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT CW/CCW1");
//     }
// }
// void ui_event_Switch8(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT ON/OFF1");
//     }
// }
void ui_event_ButtonSimpan3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBox3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
//  
void ui_event_ButtonKembali4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ArcSpeed5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed5, target, "", "");
    }
}
void ui_event_LabelSpeed5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed5, target, "", "");
    }
}
void ui_event_CheckboxState8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}
// void ui_event_SliderSpeed5(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED) {
//         _ui_slider_set_text_value(ui_LabelSpeed5, target, "", "");
//     }
// }
// void ui_event_Switch9(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT CW/CCW1");
//     }
// }
// void ui_event_Switch10(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT ON/OFF1");
//     }
// }
void ui_event_ButtonSimpan4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBox4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
// void ui_event_Button19(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_Button20(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
void ui_event_ButtonKembali5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ArcSpeed6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed6, target, "", "");
    }
}
void ui_event_LabelSpeed6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed6, target, "", "");
    }
}
void ui_event_CheckboxState11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}
// void ui_event_SliderSpeed6(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED) {
//         _ui_slider_set_text_value(ui_LabelSpeed6, target, "", "");
//     }
// }
// void ui_event_Switch11(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT CW/CCW1");
//     }
// }
// void ui_event_Switch12(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT ON/OFF1");
//     }
// }
void ui_event_ButtonSimpan5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBox5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
// void ui_event_Button21(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_Button22(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
void ui_event_ButtonKembali6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ArcSpeed7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed7, target, "", "");
    }
}
void ui_event_LabelSpeed7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed7, target, "", "");
    }
}
void ui_event_CheckboxState13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}
// void ui_event_SliderSpeed7(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED) {
//         _ui_slider_set_text_value(ui_LabelSpeed7, target, "", "");
//     }
// }
// void ui_event_Switch13(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT CW/CCW1");
//     }
// }
// void ui_event_Switch14(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT ON/OFF1");
//     }
// }
void ui_event_ButtonSimpan6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBox6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
// void ui_event_Button23(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_Button24(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
void ui_event_ButtonKembali7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ArcSpeed8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed8, target, "", "");
    }
}
void ui_event_LabelSpeed8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed8, target, "", "");
    }
}
void ui_event_CheckboxState15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}
// void ui_event_SliderSpeed8(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED) {
//         _ui_slider_set_text_value(ui_LabelSpeed8, target, "", "");
//     }
// }
// void ui_event_Switch15(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT CW/CCW1");
//     }
// }
// void ui_event_Switch16(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT ON/OFF1");
//     }
// }
void ui_event_ButtonSimpan7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBox7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
// void ui_event_Button25(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_Button26(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
void ui_event_ButtonKembali8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ArcSpeed9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed9, target, "", "");
    }
}
void ui_event_LabelSpeed9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_LabelSpeed9, target, "", "");
    }
}
void ui_event_CheckboxState17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "ON");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_LebelState1, _UI_LABEL_PROPERTY_TEXT, "OFF");
    }
}
// void ui_event_SliderSpeed9(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_VALUE_CHANGED) {
//         _ui_slider_set_text_value(ui_LabelSpeed9, target, "", "");
//     }
// }
// void ui_event_Switch17(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT CW/CCW1");
//     }
// }
// void ui_event_Switch18(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "INI EDIT ON/OFF1");
//     }
// }
void ui_event_ButtonSimpan8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBox8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
// void ui_event_Button27(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
// void ui_event_Button28(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_flag_modify(ui_ContainerMsgBox8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
//     }
// }
void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBoxREMOVEEP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Button30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBoxREMOVEFB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Button35(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBoxREMOVEEP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBoxREMOVEEP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button38(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBoxREMOVEFB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button39(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBoxREMOVEFB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Button32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBoxWIFI, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Button37(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBoxWIFI, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerMsgBoxWIFI, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_ButtonKembali12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_MainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_BLDC_1_screen_init();
    ui_BLDC_2_screen_init();
    ui_BLDC_3_screen_init();
    ui_BLDC_4_screen_init();
    ui_BLDC_5_screen_init();
    ui_BLDC_6_screen_init();
    ui_BLDC_7_screen_init();
    ui_BLDC_8_screen_init();
    ui_BLDC_9_screen_init();
    ui_ScreenSettings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
