// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320

#ifndef _UI_LCD_480X320_UI_H
#define _UI_LCD_480X320_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel23;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_KONTROL_BLDC;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_Suhu;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_LabelSpeed;
extern lv_obj_t * ui_Kecepatan;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Tekanan;
extern lv_obj_t * ui_LabelPress;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Kebisingan;
extern lv_obj_t * ui_LabelNoise;
extern lv_obj_t * ui_LebelState1;
extern lv_obj_t * ui_LebelState2;
extern lv_obj_t * ui_LebelState3;
extern lv_obj_t * ui_LebelState4;
extern lv_obj_t * ui_LebelState5;
extern lv_obj_t * ui_LebelState6;
extern lv_obj_t * ui_LebelState7;
extern lv_obj_t * ui_LebelState8;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_LebelState9;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_STATUS;
// SCREEN: ui_BLDC_1
void ui_BLDC_1_screen_init(void);
extern lv_obj_t * ui_BLDC_1;
extern lv_obj_t * ui_BLDC1;
void ui_event_ButtonKembali(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali;
extern lv_obj_t * ui_LabelKembali;
void ui_event_ArcSpeed1(lv_event_t * e);
extern lv_obj_t * ui_ArcSpeed1;
void ui_event_LabelSpeed1(lv_event_t * e);
extern lv_obj_t * ui_LabelSpeed1;
void ui_event_CheckboxState1(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState1;
void ui_event_SliderSpeed1(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_CheckboxState10;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label25;
void ui_event_ButtonSimpan(lv_event_t * e);
extern lv_obj_t * ui_ButtonSimpan;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_ContainerMsgBox;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Button14;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label26;
// SCREEN: ui_BLDC_2
void ui_BLDC_2_screen_init(void);
extern lv_obj_t * ui_BLDC_2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_BLDC2;
void ui_event_ButtonKembali1(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali1;
extern lv_obj_t * ui_LabelKembali1;
void ui_event_ArcSpeed2(lv_event_t * e);
extern lv_obj_t * ui_ArcSpeed2;
void ui_event_LabelSpeed2(lv_event_t * e);
extern lv_obj_t * ui_LabelSpeed2;
void ui_event_CheckboxState2(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState2;
void ui_event_SliderSpeed2(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed2;
extern lv_obj_t * ui_Label14;
void ui_event_CheckboxState3(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState3;
// SCREEN: ui_BLDC_3
void ui_BLDC_3_screen_init(void);
extern lv_obj_t * ui_BLDC_3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_BLDC3;
void ui_event_ButtonKembali2(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali2;
extern lv_obj_t * ui_LabelKembali2;
void ui_event_ArcSpeed3(lv_event_t * e);
extern lv_obj_t * ui_ArcSpeed3;
void ui_event_LabelSpeed3(lv_event_t * e);
extern lv_obj_t * ui_LabelSpeed3;
void ui_event_CheckboxState4(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState4;
void ui_event_SliderSpeed3(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed3;
extern lv_obj_t * ui_Label15;
void ui_event_CheckboxState5(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState5;
// SCREEN: ui_BLDC_4
void ui_BLDC_4_screen_init(void);
extern lv_obj_t * ui_BLDC_4;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_BLDC4;
void ui_event_ButtonKembali3(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali3;
extern lv_obj_t * ui_LabelKembali3;
void ui_event_ArcSpeed4(lv_event_t * e);
extern lv_obj_t * ui_ArcSpeed4;
void ui_event_LabelSpeed4(lv_event_t * e);
extern lv_obj_t * ui_LabelSpeed4;
void ui_event_CheckboxState6(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState6;
void ui_event_SliderSpeed4(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed4;
extern lv_obj_t * ui_Label16;
void ui_event_CheckboxState7(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState7;
// SCREEN: ui_BLDC_5
void ui_BLDC_5_screen_init(void);
extern lv_obj_t * ui_BLDC_5;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_BLDC5;
void ui_event_ButtonKembali4(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali4;
extern lv_obj_t * ui_LabelKembali4;
void ui_event_ArcSpeed5(lv_event_t * e);
extern lv_obj_t * ui_ArcSpeed5;
void ui_event_LabelSpeed5(lv_event_t * e);
extern lv_obj_t * ui_LabelSpeed5;
void ui_event_CheckboxState8(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState8;
void ui_event_SliderSpeed5(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed5;
extern lv_obj_t * ui_Label17;
void ui_event_CheckboxState9(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState9;
// SCREEN: ui_BLDC_6
void ui_BLDC_6_screen_init(void);
extern lv_obj_t * ui_BLDC_6;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_BLDC6;
void ui_event_ButtonKembali5(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali5;
extern lv_obj_t * ui_LabelKembali5;
void ui_event_ArcSpeed6(lv_event_t * e);
extern lv_obj_t * ui_ArcSpeed6;
void ui_event_LabelSpeed6(lv_event_t * e);
extern lv_obj_t * ui_LabelSpeed6;
void ui_event_CheckboxState11(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState11;
void ui_event_SliderSpeed6(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed6;
extern lv_obj_t * ui_Label18;
void ui_event_CheckboxState12(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState12;
// SCREEN: ui_BLDC_7
void ui_BLDC_7_screen_init(void);
extern lv_obj_t * ui_BLDC_7;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_BLDC7;
void ui_event_ButtonKembali6(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali6;
extern lv_obj_t * ui_LabelKembali6;
void ui_event_ArcSpeed7(lv_event_t * e);
extern lv_obj_t * ui_ArcSpeed7;
void ui_event_LabelSpeed7(lv_event_t * e);
extern lv_obj_t * ui_LabelSpeed7;
void ui_event_CheckboxState13(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState13;
void ui_event_SliderSpeed7(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed7;
extern lv_obj_t * ui_Label19;
void ui_event_CheckboxState14(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState14;
// SCREEN: ui_BLDC_8
void ui_BLDC_8_screen_init(void);
extern lv_obj_t * ui_BLDC_8;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_BLDC8;
void ui_event_ButtonKembali7(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali7;
extern lv_obj_t * ui_LabelKembali7;
void ui_event_ArcSpeed8(lv_event_t * e);
extern lv_obj_t * ui_ArcSpeed8;
void ui_event_LabelSpeed8(lv_event_t * e);
extern lv_obj_t * ui_LabelSpeed8;
void ui_event_CheckboxState15(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState15;
void ui_event_SliderSpeed8(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed8;
extern lv_obj_t * ui_Label20;
void ui_event_CheckboxState16(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState16;
// SCREEN: ui_BLDC_9
void ui_BLDC_9_screen_init(void);
extern lv_obj_t * ui_BLDC_9;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_BLDC9;
void ui_event_ButtonKembali8(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali8;
extern lv_obj_t * ui_LabelKembali8;
void ui_event_ArcSpeed9(lv_event_t * e);
extern lv_obj_t * ui_ArcSpeed9;
void ui_event_LabelSpeed9(lv_event_t * e);
extern lv_obj_t * ui_LabelSpeed9;
void ui_event_CheckboxState17(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState17;
void ui_event_SliderSpeed9(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed9;
extern lv_obj_t * ui_Label21;
void ui_event_CheckboxState18(lv_event_t * e);
extern lv_obj_t * ui_CheckboxState18;
// SCREEN: ui_WIFI_Screen
void ui_WIFI_Screen_screen_init(void);
extern lv_obj_t * ui_WIFI_Screen;
extern lv_obj_t * ui_Panel22;
void ui_event_ButtonKembali10(lv_event_t * e);
extern lv_obj_t * ui_ButtonKembali10;
extern lv_obj_t * ui_LabelKembali10;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1754639307);    // assets/icons8-temperature-35.png
LV_IMG_DECLARE(ui_img_1924603646);    // assets/icons8-speed-35.png
LV_IMG_DECLARE(ui_img_112426812);    // assets/icons8-pressure-35.png
LV_IMG_DECLARE(ui_img_1318045025);    // assets/icons8-noise-35.png
LV_IMG_DECLARE(ui_img_1377203910);    // assets/icons8-wi-fi-disconnected-18.png
LV_IMG_DECLARE(ui_img_777776686);    // assets/icons8-rotate-left-35.png
LV_IMG_DECLARE(ui_img_1782230515);    // assets/icons8-rotate-right-35.png
LV_IMG_DECLARE(ui_img_475571255);    // assets/icons8-wifi-18.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
