// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
void ui_event_Label7(lv_event_t * e);
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
// SCREEN: ui_BLDC_1
void ui_BLDC_1_screen_init(void);
extern lv_obj_t * ui_BLDC_1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label14;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Dropdown1;
// SCREEN: ui_BLDC_2
void ui_BLDC_2_screen_init(void);
extern lv_obj_t * ui_BLDC_2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label25;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label29;
void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
// SCREEN: ui_BLDC_3
void ui_BLDC_3_screen_init(void);
extern lv_obj_t * ui_BLDC_3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label30;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label34;
void ui_event_Dropdown3(lv_event_t * e);
extern lv_obj_t * ui_Dropdown3;
// SCREEN: ui_BLDC_4
void ui_BLDC_4_screen_init(void);
extern lv_obj_t * ui_BLDC_4;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label35;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label39;
void ui_event_Dropdown4(lv_event_t * e);
extern lv_obj_t * ui_Dropdown4;
// SCREEN: ui_BLDC_5
void ui_BLDC_5_screen_init(void);
extern lv_obj_t * ui_BLDC_5;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label40;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label44;
void ui_event_Dropdown5(lv_event_t * e);
extern lv_obj_t * ui_Dropdown5;
// SCREEN: ui_BLDC_6
void ui_BLDC_6_screen_init(void);
extern lv_obj_t * ui_BLDC_6;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label45;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Arc6;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label49;
void ui_event_Dropdown6(lv_event_t * e);
extern lv_obj_t * ui_Dropdown6;
// SCREEN: ui_BLDC_7
void ui_BLDC_7_screen_init(void);
extern lv_obj_t * ui_BLDC_7;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label50;
void ui_event_Button28(lv_event_t * e);
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Arc7;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Button29;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Label54;
void ui_event_Dropdown7(lv_event_t * e);
extern lv_obj_t * ui_Dropdown7;
// SCREEN: ui_BLDC_8
void ui_BLDC_8_screen_init(void);
extern lv_obj_t * ui_BLDC_8;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label55;
void ui_event_Button31(lv_event_t * e);
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Arc8;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Label59;
void ui_event_Dropdown8(lv_event_t * e);
extern lv_obj_t * ui_Dropdown8;
// SCREEN: ui_BLDC_9
void ui_BLDC_9_screen_init(void);
extern lv_obj_t * ui_BLDC_9;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label60;
void ui_event_Button34(lv_event_t * e);
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Arc9;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_Button35;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_Button36;
extern lv_obj_t * ui_Label64;
void ui_event_Dropdown9(lv_event_t * e);
extern lv_obj_t * ui_Dropdown9;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1754639307);    // assets/icons8-temperature-35.png
LV_IMG_DECLARE(ui_img_1924603646);    // assets/icons8-speed-35.png
LV_IMG_DECLARE(ui_img_112426812);    // assets/icons8-pressure-35.png
LV_IMG_DECLARE(ui_img_1318045025);    // assets/icons8-noise-35.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
