// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320

#ifndef _UI_LCD_480X320_UI_H
#define _UI_LCD_480X320_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label55;
// SCREEN: ui_BLDC_1
void ui_BLDC_1_screen_init(void);
extern lv_obj_t * ui_BLDC_1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label14;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label15;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
void ui_event_Label22(lv_event_t * e);
extern lv_obj_t * ui_Label22;
void ui_event_Checkbox2(lv_event_t * e);
extern lv_obj_t * ui_Checkbox2;
// SCREEN: ui_BLDC_2
void ui_BLDC_2_screen_init(void);
extern lv_obj_t * ui_BLDC_2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label23;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label24;
void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
void ui_event_Label25(lv_event_t * e);
extern lv_obj_t * ui_Label25;
void ui_event_Checkbox1(lv_event_t * e);
extern lv_obj_t * ui_Checkbox1;
// SCREEN: ui_BLDC_3
void ui_BLDC_3_screen_init(void);
extern lv_obj_t * ui_BLDC_3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label26;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label27;
void ui_event_Arc3(lv_event_t * e);
extern lv_obj_t * ui_Arc3;
void ui_event_Label28(lv_event_t * e);
extern lv_obj_t * ui_Label28;
void ui_event_Checkbox3(lv_event_t * e);
extern lv_obj_t * ui_Checkbox3;
// SCREEN: ui_BLDC_4
void ui_BLDC_4_screen_init(void);
extern lv_obj_t * ui_BLDC_4;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label29;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label30;
void ui_event_Arc4(lv_event_t * e);
extern lv_obj_t * ui_Arc4;
void ui_event_Label31(lv_event_t * e);
extern lv_obj_t * ui_Label31;
void ui_event_Checkbox4(lv_event_t * e);
extern lv_obj_t * ui_Checkbox4;
// SCREEN: ui_BLDC_5
void ui_BLDC_5_screen_init(void);
extern lv_obj_t * ui_BLDC_5;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label32;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label33;
void ui_event_Arc5(lv_event_t * e);
extern lv_obj_t * ui_Arc5;
void ui_event_Label34(lv_event_t * e);
extern lv_obj_t * ui_Label34;
void ui_event_Checkbox5(lv_event_t * e);
extern lv_obj_t * ui_Checkbox5;
// SCREEN: ui_BLDC_6
void ui_BLDC_6_screen_init(void);
extern lv_obj_t * ui_BLDC_6;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label35;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label36;
void ui_event_Arc6(lv_event_t * e);
extern lv_obj_t * ui_Arc6;
void ui_event_Label37(lv_event_t * e);
extern lv_obj_t * ui_Label37;
void ui_event_Checkbox6(lv_event_t * e);
extern lv_obj_t * ui_Checkbox6;
// SCREEN: ui_BLDC_7
void ui_BLDC_7_screen_init(void);
extern lv_obj_t * ui_BLDC_7;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label38;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label39;
void ui_event_Arc7(lv_event_t * e);
extern lv_obj_t * ui_Arc7;
void ui_event_Label40(lv_event_t * e);
extern lv_obj_t * ui_Label40;
void ui_event_Checkbox7(lv_event_t * e);
extern lv_obj_t * ui_Checkbox7;
// SCREEN: ui_BLDC_8
void ui_BLDC_8_screen_init(void);
extern lv_obj_t * ui_BLDC_8;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label41;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label42;
void ui_event_Arc8(lv_event_t * e);
extern lv_obj_t * ui_Arc8;
void ui_event_Label43(lv_event_t * e);
extern lv_obj_t * ui_Label43;
void ui_event_Checkbox8(lv_event_t * e);
extern lv_obj_t * ui_Checkbox8;
// SCREEN: ui_BLDC_9
void ui_BLDC_9_screen_init(void);
extern lv_obj_t * ui_BLDC_9;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label44;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label45;
void ui_event_Arc9(lv_event_t * e);
extern lv_obj_t * ui_Arc9;
void ui_event_Label46(lv_event_t * e);
extern lv_obj_t * ui_Label46;
void ui_event_Checkbox9(lv_event_t * e);
extern lv_obj_t * ui_Checkbox9;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1754639307);    // assets/icons8-temperature-35.png
LV_IMG_DECLARE(ui_img_1924603646);    // assets/icons8-speed-35.png
LV_IMG_DECLARE(ui_img_112426812);    // assets/icons8-pressure-35.png
LV_IMG_DECLARE(ui_img_1318045025);    // assets/icons8-noise-35.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
