// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320_1

#include "ui.h"

void ui_BLDC_5_screen_init(void)
{
    ui_BLDC_5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_5, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_BLDC_5);
    lv_obj_set_width(ui_Panel11, 307);
    lv_obj_set_height(ui_Panel11, 315);
    lv_obj_set_x(ui_Panel11, -84);
    lv_obj_set_y(ui_Panel11, -1);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_BLDC_5);
    lv_obj_set_width(ui_Panel12, 167);
    lv_obj_set_height(ui_Panel12, 317);
    lv_obj_set_x(ui_Panel12, 155);
    lv_obj_set_y(ui_Panel12, -2);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLDC5 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_BLDC5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLDC5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLDC5, -82);
    lv_obj_set_y(ui_BLDC5, -105);
    lv_obj_set_align(ui_BLDC5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLDC5, "BLDC 5");
    lv_obj_set_style_text_color(ui_BLDC5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLDC5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLDC5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali4 = lv_btn_create(ui_BLDC_5);
    lv_obj_set_width(ui_ButtonKembali4, 124);
    lv_obj_set_height(ui_ButtonKembali4, 34);
    lv_obj_set_x(ui_ButtonKembali4, 156);
    lv_obj_set_y(ui_ButtonKembali4, 124);
    lv_obj_set_align(ui_ButtonKembali4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali4, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali4 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_LabelKembali4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali4, 158);
    lv_obj_set_y(ui_LabelKembali4, 123);
    lv_obj_set_align(ui_LabelKembali4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali4, "KEMBALI");

    ui_ArcSpeed5 = lv_arc_create(ui_BLDC_5);
    lv_obj_set_width(ui_ArcSpeed5, 170);
    lv_obj_set_height(ui_ArcSpeed5, 170);
    lv_obj_set_x(ui_ArcSpeed5, -84);
    lv_obj_set_y(ui_ArcSpeed5, 24);
    lv_obj_set_align(ui_ArcSpeed5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcSpeed5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_range(ui_ArcSpeed5, 0, 180);
    lv_arc_set_value(ui_ArcSpeed5, 0);


    ui_LabelSpeed5 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_LabelSpeed5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed5, -82);
    lv_obj_set_y(ui_LabelSpeed5, -9);
    lv_obj_set_align(ui_LabelSpeed5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed5, "0");
    lv_obj_set_style_text_color(ui_LabelSpeed5, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxState8 = lv_checkbox_create(ui_BLDC_5);
    lv_checkbox_set_text(ui_CheckboxState8, "ON/OFF");
    lv_obj_set_width(ui_CheckboxState8, 90);
    lv_obj_set_height(ui_CheckboxState8, 25);
    lv_obj_set_x(ui_CheckboxState8, 154);
    lv_obj_set_y(ui_CheckboxState8, 10);
    lv_obj_set_align(ui_CheckboxState8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxState8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSpeed5 = lv_slider_create(ui_BLDC_5);
    lv_slider_set_value(ui_SliderSpeed5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed5, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed5, 209);
    lv_obj_set_height(ui_SliderSpeed5, 14);
    lv_obj_set_x(ui_SliderSpeed5, -80);
    lv_obj_set_y(ui_SliderSpeed5, 63);
    lv_obj_set_align(ui_SliderSpeed5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderSpeed5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed5, lv_color_hex(0x7DFF69), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed5, lv_color_hex(0x7DFF69), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -84);
    lv_obj_set_y(ui_Label17, -72);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "");

    ui_CheckboxState9 = lv_checkbox_create(ui_BLDC_5);
    lv_checkbox_set_text(ui_CheckboxState9, "CW/CCW");
    lv_obj_set_width(ui_CheckboxState9, 94);
    lv_obj_set_height(ui_CheckboxState9, 25);
    lv_obj_set_x(ui_CheckboxState9, 153);
    lv_obj_set_y(ui_CheckboxState9, -31);
    lv_obj_set_align(ui_CheckboxState9, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxState9, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_CheckboxState9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonKembali4, ui_event_ButtonKembali4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSpeed5, ui_event_ArcSpeed5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelSpeed5, ui_event_LabelSpeed5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState8, ui_event_CheckboxState8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed5, ui_event_SliderSpeed5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState9, ui_event_CheckboxState9, LV_EVENT_ALL, NULL);

}
