// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: test

#include "ui.h"

void ui_BLDC_8_screen_init(void)
{
    ui_BLDC_8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_8, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_BLDC_8);
    lv_obj_set_width(ui_Panel17, 307);
    lv_obj_set_height(ui_Panel17, 315);
    lv_obj_set_x(ui_Panel17, -84);
    lv_obj_set_y(ui_Panel17, -1);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_BLDC_8);
    lv_obj_set_width(ui_Panel18, 167);
    lv_obj_set_height(ui_Panel18, 317);
    lv_obj_set_x(ui_Panel18, 155);
    lv_obj_set_y(ui_Panel18, -1);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_BLDC_8);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, -84);
    lv_obj_set_y(ui_Label55, -125);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "BLDC 8");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button31 = lv_btn_create(ui_BLDC_8);
    lv_obj_set_width(ui_Button31, 124);
    lv_obj_set_height(ui_Button31, 34);
    lv_obj_set_x(ui_Button31, 156);
    lv_obj_set_y(ui_Button31, 124);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button31, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_BLDC_8);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, 158);
    lv_obj_set_y(ui_Label56, 123);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "KEMBALI");

    ui_Arc8 = lv_arc_create(ui_BLDC_8);
    lv_obj_set_width(ui_Arc8, 150);
    lv_obj_set_height(ui_Arc8, 150);
    lv_obj_set_x(ui_Arc8, -118);
    lv_obj_set_y(ui_Arc8, -1);
    lv_obj_set_align(ui_Arc8, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc8, 50);


    ui_Label57 = lv_label_create(ui_BLDC_8);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label57, -118);
    lv_obj_set_y(ui_Label57, 0);
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "0");
    lv_obj_set_style_text_color(ui_Label57, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label57, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label57, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button32 = lv_btn_create(ui_BLDC_8);
    lv_obj_set_width(ui_Button32, 44);
    lv_obj_set_height(ui_Button32, 41);
    lv_obj_set_x(ui_Button32, 15);
    lv_obj_set_y(ui_Button32, -41);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);

    ui_Label58 = lv_label_create(ui_BLDC_8);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, 15);
    lv_obj_set_y(ui_Label58, -42);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "+");
    lv_obj_set_style_text_color(ui_Label58, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button33 = lv_btn_create(ui_BLDC_8);
    lv_obj_set_width(ui_Button33, 44);
    lv_obj_set_height(ui_Button33, 41);
    lv_obj_set_x(ui_Button33, 16);
    lv_obj_set_y(ui_Button33, 12);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);

    ui_Label59 = lv_label_create(ui_BLDC_8);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, 17);
    lv_obj_set_y(ui_Label59, 12);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "-");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown8 = lv_dropdown_create(ui_BLDC_8);
    lv_dropdown_set_options(ui_Dropdown8, "OFF\nON");
    lv_dropdown_set_selected_highlight(ui_Dropdown8, false);
    lv_obj_set_width(ui_Dropdown8, 226);
    lv_obj_set_height(ui_Dropdown8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown8, -73);
    lv_obj_set_y(ui_Dropdown8, 103);
    lv_obj_set_align(ui_Dropdown8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_Button31, ui_event_Button31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown8, ui_event_Dropdown8, LV_EVENT_ALL, NULL);

}
