// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: test

#include "ui.h"

void ui_BLDC_5_screen_init(void)
{
    ui_BLDC_5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_5, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_BLDC_5);
    lv_obj_set_width(ui_Panel11, 307);
    lv_obj_set_height(ui_Panel11, 315);
    lv_obj_set_x(ui_Panel11, -84);
    lv_obj_set_y(ui_Panel11, -1);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_BLDC_5);
    lv_obj_set_width(ui_Panel12, 167);
    lv_obj_set_height(ui_Panel12, 317);
    lv_obj_set_x(ui_Panel12, 155);
    lv_obj_set_y(ui_Panel12, -1);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -84);
    lv_obj_set_y(ui_Label40, -125);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "BLDC 5");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button22 = lv_btn_create(ui_BLDC_5);
    lv_obj_set_width(ui_Button22, 124);
    lv_obj_set_height(ui_Button22, 34);
    lv_obj_set_x(ui_Button22, 156);
    lv_obj_set_y(ui_Button22, 124);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button22, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 158);
    lv_obj_set_y(ui_Label41, 123);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "KEMBALI");

    ui_Arc5 = lv_arc_create(ui_BLDC_5);
    lv_obj_set_width(ui_Arc5, 150);
    lv_obj_set_height(ui_Arc5, 150);
    lv_obj_set_x(ui_Arc5, -118);
    lv_obj_set_y(ui_Arc5, -1);
    lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc5, 50);


    ui_Label42 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -118);
    lv_obj_set_y(ui_Label42, 0);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "0");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button23 = lv_btn_create(ui_BLDC_5);
    lv_obj_set_width(ui_Button23, 44);
    lv_obj_set_height(ui_Button23, 41);
    lv_obj_set_x(ui_Button23, 15);
    lv_obj_set_y(ui_Button23, -41);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);

    ui_Label43 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 15);
    lv_obj_set_y(ui_Label43, -42);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "+");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button24 = lv_btn_create(ui_BLDC_5);
    lv_obj_set_width(ui_Button24, 44);
    lv_obj_set_height(ui_Button24, 41);
    lv_obj_set_x(ui_Button24, 16);
    lv_obj_set_y(ui_Button24, 12);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);

    ui_Label44 = lv_label_create(ui_BLDC_5);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, 17);
    lv_obj_set_y(ui_Label44, 12);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "-");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown5 = lv_dropdown_create(ui_BLDC_5);
    lv_dropdown_set_options(ui_Dropdown5, "OFF\nON\n");
    lv_dropdown_set_selected_highlight(ui_Dropdown5, false);
    lv_obj_set_width(ui_Dropdown5, 226);
    lv_obj_set_height(ui_Dropdown5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown5, -73);
    lv_obj_set_y(ui_Dropdown5, 103);
    lv_obj_set_align(ui_Dropdown5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown5, ui_event_Dropdown5, LV_EVENT_ALL, NULL);

}
