// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320

#include "ui.h"

void ui_BLDC_9_screen_init(void)
{
    ui_BLDC_9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_9, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_BLDC_9);
    lv_obj_set_width(ui_Panel19, 307);
    lv_obj_set_height(ui_Panel19, 315);
    lv_obj_set_x(ui_Panel19, -84);
    lv_obj_set_y(ui_Panel19, -1);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_BLDC_9);
    lv_obj_set_width(ui_Panel20, 167);
    lv_obj_set_height(ui_Panel20, 317);
    lv_obj_set_x(ui_Panel20, 155);
    lv_obj_set_y(ui_Panel20, -2);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLDC9 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_BLDC9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLDC9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLDC9, -82);
    lv_obj_set_y(ui_BLDC9, -105);
    lv_obj_set_align(ui_BLDC9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLDC9, "BLDC 9");
    lv_obj_set_style_text_color(ui_BLDC9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLDC9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLDC9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali8 = lv_btn_create(ui_BLDC_9);
    lv_obj_set_width(ui_ButtonKembali8, 124);
    lv_obj_set_height(ui_ButtonKembali8, 34);
    lv_obj_set_x(ui_ButtonKembali8, 156);
    lv_obj_set_y(ui_ButtonKembali8, 124);
    lv_obj_set_align(ui_ButtonKembali8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali8, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali8 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_LabelKembali8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali8, 158);
    lv_obj_set_y(ui_LabelKembali8, 123);
    lv_obj_set_align(ui_LabelKembali8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali8, "KEMBALI");

    ui_ArcSpeed9 = lv_arc_create(ui_BLDC_9);
    lv_obj_set_width(ui_ArcSpeed9, 170);
    lv_obj_set_height(ui_ArcSpeed9, 170);
    lv_obj_set_x(ui_ArcSpeed9, -84);
    lv_obj_set_y(ui_ArcSpeed9, 24);
    lv_obj_set_align(ui_ArcSpeed9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcSpeed9, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_range(ui_ArcSpeed9, 0, 180);
    lv_arc_set_value(ui_ArcSpeed9, 0);


    ui_LabelSpeed9 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_LabelSpeed9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed9, -82);
    lv_obj_set_y(ui_LabelSpeed9, -9);
    lv_obj_set_align(ui_LabelSpeed9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed9, "0");
    lv_obj_set_style_text_color(ui_LabelSpeed9, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxState17 = lv_checkbox_create(ui_BLDC_9);
    lv_checkbox_set_text(ui_CheckboxState17, "ON/OFF");
    lv_obj_set_width(ui_CheckboxState17, 90);
    lv_obj_set_height(ui_CheckboxState17, 25);
    lv_obj_set_x(ui_CheckboxState17, 154);
    lv_obj_set_y(ui_CheckboxState17, 10);
    lv_obj_set_align(ui_CheckboxState17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxState17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSpeed9 = lv_slider_create(ui_BLDC_9);
    lv_slider_set_value(ui_SliderSpeed9, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed9) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed9, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed9, 209);
    lv_obj_set_height(ui_SliderSpeed9, 14);
    lv_obj_set_x(ui_SliderSpeed9, -80);
    lv_obj_set_y(ui_SliderSpeed9, 63);
    lv_obj_set_align(ui_SliderSpeed9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderSpeed9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed9, lv_color_hex(0x7DFF69), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed9, lv_color_hex(0x7DFF69), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed9, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -84);
    lv_obj_set_y(ui_Label21, -72);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "");

    ui_CheckboxState18 = lv_checkbox_create(ui_BLDC_9);
    lv_checkbox_set_text(ui_CheckboxState18, "CW/CCW");
    lv_obj_set_width(ui_CheckboxState18, 94);
    lv_obj_set_height(ui_CheckboxState18, 25);
    lv_obj_set_x(ui_CheckboxState18, 153);
    lv_obj_set_y(ui_CheckboxState18, -31);
    lv_obj_set_align(ui_CheckboxState18, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxState18, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_CheckboxState18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonKembali8, ui_event_ButtonKembali8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSpeed9, ui_event_ArcSpeed9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelSpeed9, ui_event_LabelSpeed9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState17, ui_event_CheckboxState17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed9, ui_event_SliderSpeed9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState18, ui_event_CheckboxState18, LV_EVENT_ALL, NULL);

}
