// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320

#include "ui.h"

void ui_BLDC_1_screen_init(void)
{
    ui_BLDC_1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_1, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_BLDC_1);
    lv_obj_set_width(ui_Panel3, 307);
    lv_obj_set_height(ui_Panel3, 315);
    lv_obj_set_x(ui_Panel3, -84);
    lv_obj_set_y(ui_Panel3, -1);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_BLDC_1);
    lv_obj_set_width(ui_Panel5, 167);
    lv_obj_set_height(ui_Panel5, 317);
    lv_obj_set_x(ui_Panel5, 155);
    lv_obj_set_y(ui_Panel5, -1);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLDC1 = lv_label_create(ui_BLDC_1);
    lv_obj_set_width(ui_BLDC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLDC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLDC1, -82);
    lv_obj_set_y(ui_BLDC1, -110);
    lv_obj_set_align(ui_BLDC1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLDC1, "BLDC 1");
    lv_obj_set_style_text_color(ui_BLDC1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLDC1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLDC1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali = lv_btn_create(ui_BLDC_1);
    lv_obj_set_width(ui_ButtonKembali, 124);
    lv_obj_set_height(ui_ButtonKembali, 34);
    lv_obj_set_x(ui_ButtonKembali, 156);
    lv_obj_set_y(ui_ButtonKembali, 124);
    lv_obj_set_align(ui_ButtonKembali, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali = lv_label_create(ui_BLDC_1);
    lv_obj_set_width(ui_LabelKembali, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali, 158);
    lv_obj_set_y(ui_LabelKembali, 123);
    lv_obj_set_align(ui_LabelKembali, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali, "KEMBALI");

    ui_ArcSpeed1 = lv_arc_create(ui_BLDC_1);
    lv_obj_set_width(ui_ArcSpeed1, 190);
    lv_obj_set_height(ui_ArcSpeed1, 190);
    lv_obj_set_x(ui_ArcSpeed1, -84);
    lv_obj_set_y(ui_ArcSpeed1, 30);
    lv_obj_set_align(ui_ArcSpeed1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcSpeed1, 10);


    ui_LabelSpeed1 = lv_label_create(ui_BLDC_1);
    lv_obj_set_width(ui_LabelSpeed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed1, -86);
    lv_obj_set_y(ui_LabelSpeed1, 28);
    lv_obj_set_align(ui_LabelSpeed1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed1, "0");
    lv_obj_set_style_text_color(ui_LabelSpeed1, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxState1 = lv_checkbox_create(ui_BLDC_1);
    lv_checkbox_set_text(ui_CheckboxState1, "ON/OFF");
    lv_obj_set_width(ui_CheckboxState1, 92);
    lv_obj_set_height(ui_CheckboxState1, 20);
    lv_obj_set_x(ui_CheckboxState1, -82);
    lv_obj_set_y(ui_CheckboxState1, 123);
    lv_obj_set_align(ui_CheckboxState1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxState1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonKembali, ui_event_ButtonKembali, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSpeed1, ui_event_ArcSpeed1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelSpeed1, ui_event_LabelSpeed1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState1, ui_event_CheckboxState1, LV_EVENT_ALL, NULL);

}
