// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320

#include "ui.h"

void ui_BLDC_7_screen_init(void)
{
    ui_BLDC_7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_7, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_BLDC_7);
    lv_obj_set_width(ui_Panel15, 307);
    lv_obj_set_height(ui_Panel15, 315);
    lv_obj_set_x(ui_Panel15, -84);
    lv_obj_set_y(ui_Panel15, -1);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_BLDC_7);
    lv_obj_set_width(ui_Panel16, 167);
    lv_obj_set_height(ui_Panel16, 317);
    lv_obj_set_x(ui_Panel16, 155);
    lv_obj_set_y(ui_Panel16, -2);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLDC7 = lv_label_create(ui_BLDC_7);
    lv_obj_set_width(ui_BLDC7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLDC7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLDC7, -82);
    lv_obj_set_y(ui_BLDC7, -105);
    lv_obj_set_align(ui_BLDC7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLDC7, "BLDC 7");
    lv_obj_set_style_text_color(ui_BLDC7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLDC7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLDC7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali6 = lv_btn_create(ui_BLDC_7);
    lv_obj_set_width(ui_ButtonKembali6, 124);
    lv_obj_set_height(ui_ButtonKembali6, 34);
    lv_obj_set_x(ui_ButtonKembali6, 156);
    lv_obj_set_y(ui_ButtonKembali6, 124);
    lv_obj_set_align(ui_ButtonKembali6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali6, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali6 = lv_label_create(ui_BLDC_7);
    lv_obj_set_width(ui_LabelKembali6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali6, 158);
    lv_obj_set_y(ui_LabelKembali6, 123);
    lv_obj_set_align(ui_LabelKembali6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali6, "KEMBALI");

    ui_ArcSpeed7 = lv_arc_create(ui_BLDC_7);
    lv_obj_set_width(ui_ArcSpeed7, 170);
    lv_obj_set_height(ui_ArcSpeed7, 170);
    lv_obj_set_x(ui_ArcSpeed7, -84);
    lv_obj_set_y(ui_ArcSpeed7, 24);
    lv_obj_set_align(ui_ArcSpeed7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcSpeed7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_range(ui_ArcSpeed7, 0, 180);
    lv_arc_set_value(ui_ArcSpeed7, 0);


    ui_LabelSpeed7 = lv_label_create(ui_BLDC_7);
    lv_obj_set_width(ui_LabelSpeed7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed7, -82);
    lv_obj_set_y(ui_LabelSpeed7, -9);
    lv_obj_set_align(ui_LabelSpeed7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed7, "0");
    lv_obj_set_style_text_color(ui_LabelSpeed7, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxState13 = lv_checkbox_create(ui_BLDC_7);
    lv_checkbox_set_text(ui_CheckboxState13, "ON/OFF");
    lv_obj_set_width(ui_CheckboxState13, 90);
    lv_obj_set_height(ui_CheckboxState13, 25);
    lv_obj_set_x(ui_CheckboxState13, 154);
    lv_obj_set_y(ui_CheckboxState13, 10);
    lv_obj_set_align(ui_CheckboxState13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxState13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSpeed7 = lv_slider_create(ui_BLDC_7);
    lv_slider_set_value(ui_SliderSpeed7, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed7, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed7, 209);
    lv_obj_set_height(ui_SliderSpeed7, 14);
    lv_obj_set_x(ui_SliderSpeed7, -80);
    lv_obj_set_y(ui_SliderSpeed7, 63);
    lv_obj_set_align(ui_SliderSpeed7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderSpeed7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed7, lv_color_hex(0x7DFF69), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed7, lv_color_hex(0x7DFF69), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed7, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_BLDC_7);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -84);
    lv_obj_set_y(ui_Label19, -72);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "");

    ui_CheckboxState14 = lv_checkbox_create(ui_BLDC_7);
    lv_checkbox_set_text(ui_CheckboxState14, "CW/CCW");
    lv_obj_set_width(ui_CheckboxState14, 94);
    lv_obj_set_height(ui_CheckboxState14, 25);
    lv_obj_set_x(ui_CheckboxState14, 153);
    lv_obj_set_y(ui_CheckboxState14, -31);
    lv_obj_set_align(ui_CheckboxState14, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxState14, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_CheckboxState14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonKembali6, ui_event_ButtonKembali6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSpeed7, ui_event_ArcSpeed7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelSpeed7, ui_event_LabelSpeed7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState13, ui_event_CheckboxState13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed7, ui_event_SliderSpeed7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState14, ui_event_CheckboxState14, LV_EVENT_ALL, NULL);

}
