// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320

#include "ui.h"

void ui_BLDC_8_screen_init(void)
{
    ui_BLDC_8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_8, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_BLDC_8);
    lv_obj_set_width(ui_Panel17, 307);
    lv_obj_set_height(ui_Panel17, 315);
    lv_obj_set_x(ui_Panel17, -84);
    lv_obj_set_y(ui_Panel17, -1);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_BLDC_8);
    lv_obj_set_width(ui_Panel18, 167);
    lv_obj_set_height(ui_Panel18, 317);
    lv_obj_set_x(ui_Panel18, 155);
    lv_obj_set_y(ui_Panel18, -2);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLDC8 = lv_label_create(ui_BLDC_8);
    lv_obj_set_width(ui_BLDC8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLDC8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLDC8, -82);
    lv_obj_set_y(ui_BLDC8, -105);
    lv_obj_set_align(ui_BLDC8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLDC8, "BLDC 8");
    lv_obj_set_style_text_color(ui_BLDC8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLDC8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLDC8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali7 = lv_btn_create(ui_BLDC_8);
    lv_obj_set_width(ui_ButtonKembali7, 124);
    lv_obj_set_height(ui_ButtonKembali7, 34);
    lv_obj_set_x(ui_ButtonKembali7, 156);
    lv_obj_set_y(ui_ButtonKembali7, 124);
    lv_obj_set_align(ui_ButtonKembali7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali7, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali7 = lv_label_create(ui_BLDC_8);
    lv_obj_set_width(ui_LabelKembali7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali7, 158);
    lv_obj_set_y(ui_LabelKembali7, 123);
    lv_obj_set_align(ui_LabelKembali7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali7, "KEMBALI");

    ui_ArcSpeed8 = lv_arc_create(ui_BLDC_8);
    lv_obj_set_width(ui_ArcSpeed8, 170);
    lv_obj_set_height(ui_ArcSpeed8, 170);
    lv_obj_set_x(ui_ArcSpeed8, -84);
    lv_obj_set_y(ui_ArcSpeed8, 24);
    lv_obj_set_align(ui_ArcSpeed8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcSpeed8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_range(ui_ArcSpeed8, 0, 180);
    lv_arc_set_value(ui_ArcSpeed8, 0);


    ui_LabelSpeed8 = lv_label_create(ui_BLDC_8);
    lv_obj_set_width(ui_LabelSpeed8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed8, -82);
    lv_obj_set_y(ui_LabelSpeed8, -9);
    lv_obj_set_align(ui_LabelSpeed8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed8, "0");
    lv_obj_set_style_text_color(ui_LabelSpeed8, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxState15 = lv_checkbox_create(ui_BLDC_8);
    lv_checkbox_set_text(ui_CheckboxState15, "ON/OFF");
    lv_obj_set_width(ui_CheckboxState15, 90);
    lv_obj_set_height(ui_CheckboxState15, 25);
    lv_obj_set_x(ui_CheckboxState15, 154);
    lv_obj_set_y(ui_CheckboxState15, 10);
    lv_obj_set_align(ui_CheckboxState15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxState15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSpeed8 = lv_slider_create(ui_BLDC_8);
    lv_slider_set_value(ui_SliderSpeed8, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed8) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed8, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed8, 209);
    lv_obj_set_height(ui_SliderSpeed8, 14);
    lv_obj_set_x(ui_SliderSpeed8, -80);
    lv_obj_set_y(ui_SliderSpeed8, 63);
    lv_obj_set_align(ui_SliderSpeed8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderSpeed8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed8, lv_color_hex(0x7DFF69), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed8, lv_color_hex(0x7DFF69), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed8, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_BLDC_8);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -84);
    lv_obj_set_y(ui_Label20, -72);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "");

    ui_CheckboxState16 = lv_checkbox_create(ui_BLDC_8);
    lv_checkbox_set_text(ui_CheckboxState16, "CW/CCW");
    lv_obj_set_width(ui_CheckboxState16, 94);
    lv_obj_set_height(ui_CheckboxState16, 25);
    lv_obj_set_x(ui_CheckboxState16, 153);
    lv_obj_set_y(ui_CheckboxState16, -31);
    lv_obj_set_align(ui_CheckboxState16, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxState16, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_CheckboxState16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonKembali7, ui_event_ButtonKembali7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSpeed8, ui_event_ArcSpeed8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelSpeed8, ui_event_LabelSpeed8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState15, ui_event_CheckboxState15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed8, ui_event_SliderSpeed8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState16, ui_event_CheckboxState16, LV_EVENT_ALL, NULL);

}
