// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: test

#include "ui.h"

void ui_BLDC_7_screen_init(void)
{
    ui_BLDC_7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_7, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_BLDC_7);
    lv_obj_set_width(ui_Panel15, 307);
    lv_obj_set_height(ui_Panel15, 315);
    lv_obj_set_x(ui_Panel15, -84);
    lv_obj_set_y(ui_Panel15, -1);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_BLDC_7);
    lv_obj_set_width(ui_Panel16, 167);
    lv_obj_set_height(ui_Panel16, 317);
    lv_obj_set_x(ui_Panel16, 155);
    lv_obj_set_y(ui_Panel16, -1);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_BLDC_7);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -84);
    lv_obj_set_y(ui_Label50, -125);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "BLDC 7");
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button28 = lv_btn_create(ui_BLDC_7);
    lv_obj_set_width(ui_Button28, 124);
    lv_obj_set_height(ui_Button28, 34);
    lv_obj_set_x(ui_Button28, 156);
    lv_obj_set_y(ui_Button28, 124);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button28, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_BLDC_7);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 158);
    lv_obj_set_y(ui_Label51, 123);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "KEMBALI");

    ui_Arc7 = lv_arc_create(ui_BLDC_7);
    lv_obj_set_width(ui_Arc7, 150);
    lv_obj_set_height(ui_Arc7, 150);
    lv_obj_set_x(ui_Arc7, -118);
    lv_obj_set_y(ui_Arc7, -1);
    lv_obj_set_align(ui_Arc7, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc7, 50);


    ui_Label52 = lv_label_create(ui_BLDC_7);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, -118);
    lv_obj_set_y(ui_Label52, 0);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "0");
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label52, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button29 = lv_btn_create(ui_BLDC_7);
    lv_obj_set_width(ui_Button29, 44);
    lv_obj_set_height(ui_Button29, 41);
    lv_obj_set_x(ui_Button29, 15);
    lv_obj_set_y(ui_Button29, -41);
    lv_obj_set_align(ui_Button29, LV_ALIGN_CENTER);

    ui_Label53 = lv_label_create(ui_BLDC_7);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, 15);
    lv_obj_set_y(ui_Label53, -42);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "+");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button30 = lv_btn_create(ui_BLDC_7);
    lv_obj_set_width(ui_Button30, 44);
    lv_obj_set_height(ui_Button30, 41);
    lv_obj_set_x(ui_Button30, 16);
    lv_obj_set_y(ui_Button30, 12);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);

    ui_Label54 = lv_label_create(ui_BLDC_7);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, 17);
    lv_obj_set_y(ui_Label54, 12);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "-");
    lv_obj_set_style_text_color(ui_Label54, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown7 = lv_dropdown_create(ui_BLDC_7);
    lv_dropdown_set_options(ui_Dropdown7, "OFF\nON");
    lv_dropdown_set_selected_highlight(ui_Dropdown7, false);
    lv_obj_set_width(ui_Dropdown7, 226);
    lv_obj_set_height(ui_Dropdown7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown7, -73);
    lv_obj_set_y(ui_Dropdown7, 103);
    lv_obj_set_align(ui_Dropdown7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown7, ui_event_Dropdown7, LV_EVENT_ALL, NULL);

}
