// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320_v2_2

#include "ui.h"

void ui_BLDC_9_screen_init(void)
{
    ui_BLDC_9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_9, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLDC9 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_BLDC9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLDC9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLDC9, -88);
    lv_obj_set_y(ui_BLDC9, -105);
    lv_obj_set_align(ui_BLDC9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLDC9, "SPEED BLDC 9");
    lv_obj_set_style_text_color(ui_BLDC9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLDC9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLDC9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali8 = lv_btn_create(ui_BLDC_9);
    lv_obj_set_width(ui_ButtonKembali8, 124);
    lv_obj_set_height(ui_ButtonKembali8, 34);
    lv_obj_set_x(ui_ButtonKembali8, 156);
    lv_obj_set_y(ui_ButtonKembali8, 124);
    lv_obj_set_align(ui_ButtonKembali8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali8, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali8 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_LabelKembali8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali8, 158);
    lv_obj_set_y(ui_LabelKembali8, 123);
    lv_obj_set_align(ui_LabelKembali8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali8, "RETURN");

    ui_ArcSpeed9 = lv_arc_create(ui_BLDC_9);
    lv_obj_set_width(ui_ArcSpeed9, 170);
    lv_obj_set_height(ui_ArcSpeed9, 170);
    lv_obj_set_x(ui_ArcSpeed9, -84);
    lv_obj_set_y(ui_ArcSpeed9, 24);
    lv_obj_set_align(ui_ArcSpeed9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcSpeed9, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_range(ui_ArcSpeed9, 0, 180);
    lv_arc_set_value(ui_ArcSpeed9, 0);


    ui_LabelSpeed9 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_LabelSpeed9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed9, -82);
    lv_obj_set_y(ui_LabelSpeed9, -9);
    lv_obj_set_align(ui_LabelSpeed9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed9, "0");
    lv_obj_set_style_text_color(ui_LabelSpeed9, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxState17 = lv_checkbox_create(ui_BLDC_9);
    lv_checkbox_set_text(ui_CheckboxState17, "ON/OFF");
    lv_obj_set_width(ui_CheckboxState17, 90);
    lv_obj_set_height(ui_CheckboxState17, 25);
    lv_obj_set_x(ui_CheckboxState17, 154);
    lv_obj_set_y(ui_CheckboxState17, 10);
    lv_obj_set_align(ui_CheckboxState17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxState17, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSpeed9 = lv_slider_create(ui_BLDC_9);
    lv_slider_set_value(ui_SliderSpeed9, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed9) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed9, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed9, 209);
    lv_obj_set_height(ui_SliderSpeed9, 14);
    lv_obj_set_x(ui_SliderSpeed9, -80);
    lv_obj_set_y(ui_SliderSpeed9, 63);
    lv_obj_set_align(ui_SliderSpeed9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderSpeed9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed9, lv_color_hex(0x7DFF69), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed9, lv_color_hex(0x7DFF69), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed9, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label70 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label70, -84);
    lv_obj_set_y(ui_Label70, -72);
    lv_obj_set_align(ui_Label70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label70, "");

    ui_CheckboxState18 = lv_checkbox_create(ui_BLDC_9);
    lv_checkbox_set_text(ui_CheckboxState18, "CW/CCW");
    lv_obj_set_width(ui_CheckboxState18, 94);
    lv_obj_set_height(ui_CheckboxState18, 25);
    lv_obj_set_x(ui_CheckboxState18, 153);
    lv_obj_set_y(ui_CheckboxState18, -24);
    lv_obj_set_align(ui_CheckboxState18, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxState18, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_CheckboxState18, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch17 = lv_switch_create(ui_BLDC_9);
    lv_obj_set_width(ui_Switch17, 80);
    lv_obj_set_height(ui_Switch17, 40);
    lv_obj_set_x(ui_Switch17, 159);
    lv_obj_set_y(ui_Switch17, -100);
    lv_obj_set_align(ui_Switch17, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch17, lv_color_hex(0x9F9F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch17, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch17, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label71 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label71, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label71, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label71, 161);
    lv_obj_set_y(ui_Label71, -67);
    lv_obj_set_align(ui_Label71, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label71, "CW/CCW");
    lv_obj_set_style_text_color(ui_Label71, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label71, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label71, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch18 = lv_switch_create(ui_BLDC_9);
    lv_obj_set_width(ui_Switch18, 80);
    lv_obj_set_height(ui_Switch18, 40);
    lv_obj_set_x(ui_Switch18, 161);
    lv_obj_set_y(ui_Switch18, -15);
    lv_obj_set_align(ui_Switch18, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch18, lv_color_hex(0x9F9F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch18, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch18, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label72 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label72, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label72, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label72, 163);
    lv_obj_set_y(ui_Label72, 19);
    lv_obj_set_align(ui_Label72, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label72, "ON/OFF");
    lv_obj_set_style_text_color(ui_Label72, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label72, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label72, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSimpan8 = lv_btn_create(ui_BLDC_9);
    lv_obj_set_width(ui_ButtonSimpan8, 124);
    lv_obj_set_height(ui_ButtonSimpan8, 34);
    lv_obj_set_x(ui_ButtonSimpan8, 156);
    lv_obj_set_y(ui_ButtonSimpan8, 81);
    lv_obj_set_align(ui_ButtonSimpan8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonSimpan8, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSimpan8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label73 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label73, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label73, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label73, 156);
    lv_obj_set_y(ui_Label73, 81);
    lv_obj_set_align(ui_Label73, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label73, "SAVE");
    lv_obj_set_style_text_color(ui_Label73, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label73, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label73, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMsgBox8 = lv_obj_create(ui_BLDC_9);
    lv_obj_remove_style_all(ui_ContainerMsgBox8);
    lv_obj_set_width(ui_ContainerMsgBox8, 276);
    lv_obj_set_height(ui_ContainerMsgBox8, 252);
    lv_obj_set_x(ui_ContainerMsgBox8, -67);
    lv_obj_set_y(ui_ContainerMsgBox8, -11);
    lv_obj_set_align(ui_ContainerMsgBox8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerMsgBox8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerMsgBox8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel10 = lv_obj_create(ui_ContainerMsgBox8);
    lv_obj_set_width(ui_Panel10, 270);
    lv_obj_set_height(ui_Panel10, 250);
    lv_obj_set_x(ui_Panel10, 0);
    lv_obj_set_y(ui_Panel10, -1);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x2D3273), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label74 = lv_label_create(ui_ContainerMsgBox8);
    lv_obj_set_width(ui_Label74, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label74, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label74, 1);
    lv_obj_set_y(ui_Label74, -24);
    lv_obj_set_align(ui_Label74, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label74, "SAVING DATA ?");
    lv_obj_set_style_text_color(ui_Label74, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label74, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label74, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button27 = lv_btn_create(ui_ContainerMsgBox8);
    lv_obj_set_width(ui_Button27, 100);
    lv_obj_set_height(ui_Button27, 40);
    lv_obj_set_x(ui_Button27, 61);
    lv_obj_set_y(ui_Button27, 89);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button27, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button28 = lv_btn_create(ui_ContainerMsgBox8);
    lv_obj_set_width(ui_Button28, 100);
    lv_obj_set_height(ui_Button28, 40);
    lv_obj_set_x(ui_Button28, -63);
    lv_obj_set_y(ui_Button28, 89);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button28, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Button28, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label75 = lv_label_create(ui_ContainerMsgBox8);
    lv_obj_set_width(ui_Label75, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label75, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label75, -60);
    lv_obj_set_y(ui_Label75, 88);
    lv_obj_set_align(ui_Label75, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label75, "CANCEL");

    ui_Label76 = lv_label_create(ui_ContainerMsgBox8);
    lv_obj_set_width(ui_Label76, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label76, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label76, 60);
    lv_obj_set_y(ui_Label76, 88);
    lv_obj_set_align(ui_Label76, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label76, "YES");

    lv_obj_add_event_cb(ui_ButtonKembali8, ui_event_ButtonKembali8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSpeed9, ui_event_ArcSpeed9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelSpeed9, ui_event_LabelSpeed9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState17, ui_event_CheckboxState17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed9, ui_event_SliderSpeed9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch17, ui_event_Switch17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch18, ui_event_Switch18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSimpan8, ui_event_ButtonSimpan8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);

}
