// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320

#include "ui.h"

void ui_BLDC_6_screen_init(void)
{
    ui_BLDC_6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_6, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_BLDC_6);
    lv_obj_set_width(ui_Panel13, 307);
    lv_obj_set_height(ui_Panel13, 315);
    lv_obj_set_x(ui_Panel13, -84);
    lv_obj_set_y(ui_Panel13, -1);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_BLDC_6);
    lv_obj_set_width(ui_Panel14, 167);
    lv_obj_set_height(ui_Panel14, 317);
    lv_obj_set_x(ui_Panel14, 155);
    lv_obj_set_y(ui_Panel14, -2);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLDC6 = lv_label_create(ui_BLDC_6);
    lv_obj_set_width(ui_BLDC6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLDC6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLDC6, -82);
    lv_obj_set_y(ui_BLDC6, -105);
    lv_obj_set_align(ui_BLDC6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLDC6, "BLDC 6");
    lv_obj_set_style_text_color(ui_BLDC6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLDC6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLDC6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKembali5 = lv_btn_create(ui_BLDC_6);
    lv_obj_set_width(ui_ButtonKembali5, 124);
    lv_obj_set_height(ui_ButtonKembali5, 34);
    lv_obj_set_x(ui_ButtonKembali5, 156);
    lv_obj_set_y(ui_ButtonKembali5, 124);
    lv_obj_set_align(ui_ButtonKembali5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonKembali5, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonKembali5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKembali5 = lv_label_create(ui_BLDC_6);
    lv_obj_set_width(ui_LabelKembali5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKembali5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKembali5, 158);
    lv_obj_set_y(ui_LabelKembali5, 123);
    lv_obj_set_align(ui_LabelKembali5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKembali5, "KEMBALI");

    ui_ArcSpeed6 = lv_arc_create(ui_BLDC_6);
    lv_obj_set_width(ui_ArcSpeed6, 170);
    lv_obj_set_height(ui_ArcSpeed6, 170);
    lv_obj_set_x(ui_ArcSpeed6, -84);
    lv_obj_set_y(ui_ArcSpeed6, 24);
    lv_obj_set_align(ui_ArcSpeed6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcSpeed6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_range(ui_ArcSpeed6, 0, 180);
    lv_arc_set_value(ui_ArcSpeed6, 0);


    ui_LabelSpeed6 = lv_label_create(ui_BLDC_6);
    lv_obj_set_width(ui_LabelSpeed6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed6, -82);
    lv_obj_set_y(ui_LabelSpeed6, -9);
    lv_obj_set_align(ui_LabelSpeed6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed6, "0");
    lv_obj_set_style_text_color(ui_LabelSpeed6, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeed6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed6, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxState11 = lv_checkbox_create(ui_BLDC_6);
    lv_checkbox_set_text(ui_CheckboxState11, "ON/OFF");
    lv_obj_set_width(ui_CheckboxState11, 90);
    lv_obj_set_height(ui_CheckboxState11, 25);
    lv_obj_set_x(ui_CheckboxState11, 154);
    lv_obj_set_y(ui_CheckboxState11, 10);
    lv_obj_set_align(ui_CheckboxState11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxState11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSpeed6 = lv_slider_create(ui_BLDC_6);
    lv_slider_set_value(ui_SliderSpeed6, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed6, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed6, 209);
    lv_obj_set_height(ui_SliderSpeed6, 14);
    lv_obj_set_x(ui_SliderSpeed6, -80);
    lv_obj_set_y(ui_SliderSpeed6, 63);
    lv_obj_set_align(ui_SliderSpeed6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderSpeed6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed6, lv_color_hex(0x7DFF69), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed6, lv_color_hex(0x7DFF69), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed6, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_BLDC_6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -84);
    lv_obj_set_y(ui_Label18, -72);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "");

    ui_CheckboxState12 = lv_checkbox_create(ui_BLDC_6);
    lv_checkbox_set_text(ui_CheckboxState12, "CW/CCW");
    lv_obj_set_width(ui_CheckboxState12, 94);
    lv_obj_set_height(ui_CheckboxState12, 25);
    lv_obj_set_x(ui_CheckboxState12, 153);
    lv_obj_set_y(ui_CheckboxState12, -31);
    lv_obj_set_align(ui_CheckboxState12, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxState12, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_CheckboxState12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CheckboxState12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckboxState12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonKembali5, ui_event_ButtonKembali5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcSpeed6, ui_event_ArcSpeed6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelSpeed6, ui_event_LabelSpeed6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState11, ui_event_CheckboxState11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed6, ui_event_SliderSpeed6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxState12, ui_event_CheckboxState12, LV_EVENT_ALL, NULL);

}
