// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ui-lcd-480x320

#include "ui.h"

void ui_BLDC_6_screen_init(void)
{
    ui_BLDC_6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_6, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_BLDC_6);
    lv_obj_set_width(ui_Panel13, 307);
    lv_obj_set_height(ui_Panel13, 315);
    lv_obj_set_x(ui_Panel13, -84);
    lv_obj_set_y(ui_Panel13, -1);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_BLDC_6);
    lv_obj_set_width(ui_Panel14, 167);
    lv_obj_set_height(ui_Panel14, 317);
    lv_obj_set_x(ui_Panel14, 155);
    lv_obj_set_y(ui_Panel14, -1);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_BLDC_6);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -82);
    lv_obj_set_y(ui_Label35, -117);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "BLDC 6");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_btn_create(ui_BLDC_6);
    lv_obj_set_width(ui_Button15, 124);
    lv_obj_set_height(ui_Button15, 34);
    lv_obj_set_x(ui_Button15, 156);
    lv_obj_set_y(ui_Button15, 124);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_BLDC_6);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 158);
    lv_obj_set_y(ui_Label36, 123);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "KEMBALI");

    ui_Arc6 = lv_arc_create(ui_BLDC_6);
    lv_obj_set_width(ui_Arc6, 190);
    lv_obj_set_height(ui_Arc6, 190);
    lv_obj_set_x(ui_Arc6, -84);
    lv_obj_set_y(ui_Arc6, 13);
    lv_obj_set_align(ui_Arc6, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc6, 10);


    ui_Label37 = lv_label_create(ui_BLDC_6);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -85);
    lv_obj_set_y(ui_Label37, 8);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "0");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox6 = lv_checkbox_create(ui_BLDC_6);
    lv_checkbox_set_text(ui_Checkbox6, "ON/OFF");
    lv_obj_set_width(ui_Checkbox6, 92);
    lv_obj_set_height(ui_Checkbox6, 20);
    lv_obj_set_x(ui_Checkbox6, -81);
    lv_obj_set_y(ui_Checkbox6, 115);
    lv_obj_set_align(ui_Checkbox6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Checkbox6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Checkbox6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc6, ui_event_Arc6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label37, ui_event_Label37, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Checkbox6, ui_event_Checkbox6, LV_EVENT_ALL, NULL);

}
