// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: test

#include "ui.h"

void ui_BLDC_9_screen_init(void)
{
    ui_BLDC_9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLDC_9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLDC_9, lv_color_hex(0x11004A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLDC_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_BLDC_9);
    lv_obj_set_width(ui_Panel19, 307);
    lv_obj_set_height(ui_Panel19, 315);
    lv_obj_set_x(ui_Panel19, -84);
    lv_obj_set_y(ui_Panel19, -1);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_BLDC_9);
    lv_obj_set_width(ui_Panel20, 167);
    lv_obj_set_height(ui_Panel20, 317);
    lv_obj_set_x(ui_Panel20, 155);
    lv_obj_set_y(ui_Panel20, -1);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x403890), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, -84);
    lv_obj_set_y(ui_Label60, -125);
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "BLDC 9");
    lv_obj_set_style_text_color(ui_Label60, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button34 = lv_btn_create(ui_BLDC_9);
    lv_obj_set_width(ui_Button34, 124);
    lv_obj_set_height(ui_Button34, 34);
    lv_obj_set_x(ui_Button34, 156);
    lv_obj_set_y(ui_Button34, 124);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button34, lv_color_hex(0x7DFF69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, 158);
    lv_obj_set_y(ui_Label61, 123);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "KEMBALI");

    ui_Arc9 = lv_arc_create(ui_BLDC_9);
    lv_obj_set_width(ui_Arc9, 150);
    lv_obj_set_height(ui_Arc9, 150);
    lv_obj_set_x(ui_Arc9, -118);
    lv_obj_set_y(ui_Arc9, -1);
    lv_obj_set_align(ui_Arc9, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc9, 50);


    ui_Label62 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, -118);
    lv_obj_set_y(ui_Label62, 0);
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "0");
    lv_obj_set_style_text_color(ui_Label62, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label62, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label62, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button35 = lv_btn_create(ui_BLDC_9);
    lv_obj_set_width(ui_Button35, 44);
    lv_obj_set_height(ui_Button35, 41);
    lv_obj_set_x(ui_Button35, 15);
    lv_obj_set_y(ui_Button35, -41);
    lv_obj_set_align(ui_Button35, LV_ALIGN_CENTER);

    ui_Label63 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, 15);
    lv_obj_set_y(ui_Label63, -42);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "+");
    lv_obj_set_style_text_color(ui_Label63, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label63, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button36 = lv_btn_create(ui_BLDC_9);
    lv_obj_set_width(ui_Button36, 44);
    lv_obj_set_height(ui_Button36, 41);
    lv_obj_set_x(ui_Button36, 16);
    lv_obj_set_y(ui_Button36, 12);
    lv_obj_set_align(ui_Button36, LV_ALIGN_CENTER);

    ui_Label64 = lv_label_create(ui_BLDC_9);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, 17);
    lv_obj_set_y(ui_Label64, 12);
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "-");
    lv_obj_set_style_text_color(ui_Label64, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label64, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label64, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown9 = lv_dropdown_create(ui_BLDC_9);
    lv_dropdown_set_options(ui_Dropdown9, "OFF\nON\n");
    lv_dropdown_set_selected_highlight(ui_Dropdown9, false);
    lv_obj_set_width(ui_Dropdown9, 226);
    lv_obj_set_height(ui_Dropdown9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown9, -73);
    lv_obj_set_y(ui_Dropdown9, 103);
    lv_obj_set_align(ui_Dropdown9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_Button34, ui_event_Button34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown9, ui_event_Dropdown9, LV_EVENT_ALL, NULL);

}
